/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyTodo {}
  interface MyTodoAttributes extends StencilHTMLAttributes {}

  interface TodoInput {}
  interface TodoInputAttributes extends StencilHTMLAttributes {
    'onOnTodoInputSubmit'?: (event: CustomEvent) => void;
  }

  interface TodoItem {
    'checked': boolean;
    'index': number;
    'text': string;
  }
  interface TodoItemAttributes extends StencilHTMLAttributes {
    'checked'?: boolean;
    'index'?: number;
    'onOnTodoItemChecked'?: (event: CustomEvent) => void;
    'onOnTodoItemRemove'?: (event: CustomEvent) => void;
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyTodo': Components.MyTodo;
    'TodoInput': Components.TodoInput;
    'TodoItem': Components.TodoItem;
  }

  interface StencilIntrinsicElements {
    'my-todo': Components.MyTodoAttributes;
    'todo-input': Components.TodoInputAttributes;
    'todo-item': Components.TodoItemAttributes;
  }


  interface HTMLMyTodoElement extends Components.MyTodo, HTMLStencilElement {}
  var HTMLMyTodoElement: {
    prototype: HTMLMyTodoElement;
    new (): HTMLMyTodoElement;
  };

  interface HTMLTodoInputElement extends Components.TodoInput, HTMLStencilElement {}
  var HTMLTodoInputElement: {
    prototype: HTMLTodoInputElement;
    new (): HTMLTodoInputElement;
  };

  interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {}
  var HTMLTodoItemElement: {
    prototype: HTMLTodoItemElement;
    new (): HTMLTodoItemElement;
  };

  interface HTMLElementTagNameMap {
    'my-todo': HTMLMyTodoElement
    'todo-input': HTMLTodoInputElement
    'todo-item': HTMLTodoItemElement
  }

  interface ElementTagNameMap {
    'my-todo': HTMLMyTodoElement;
    'todo-input': HTMLTodoInputElement;
    'todo-item': HTMLTodoItemElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
