/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { JSXElements } from '@stencil/core';




export namespace Components {

  interface MyTodo {}
  interface MyTodoAttributes extends JSXElements.HTMLAttributes {}

  interface TodoInput {}
  interface TodoInputAttributes extends JSXElements.HTMLAttributes {}

  interface TodoItem {}
  interface TodoItemAttributes extends JSXElements.HTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyTodo': Components.MyTodo;
    'TodoInput': Components.TodoInput;
    'TodoItem': Components.TodoItem;
  }

  interface StencilIntrinsicElements {
    'my-todo': Components.MyTodoAttributes;
    'todo-input': Components.TodoInputAttributes;
    'todo-item': Components.TodoItemAttributes;
  }


  interface HTMLMyTodoElement extends Components.MyTodo, HTMLElement {}
  var HTMLMyTodoElement: {
    prototype: HTMLMyTodoElement;
    new (): HTMLMyTodoElement;
  };

  interface HTMLTodoInputElement extends Components.TodoInput, HTMLElement {}
  var HTMLTodoInputElement: {
    prototype: HTMLTodoInputElement;
    new (): HTMLTodoInputElement;
  };

  interface HTMLTodoItemElement extends Components.TodoItem, HTMLElement {}
  var HTMLTodoItemElement: {
    prototype: HTMLTodoItemElement;
    new (): HTMLTodoItemElement;
  };

  interface HTMLElementTagNameMap {
    'my-todo': HTMLMyTodoElement
    'todo-input': HTMLTodoInputElement
    'todo-item': HTMLTodoItemElement
  }

  interface ElementTagNameMap {
    'my-todo': HTMLMyTodoElement;
    'todo-input': HTMLTodoInputElement;
    'todo-item': HTMLTodoItemElement;
  }

}
