name: 'Format'
description: 'verifies stencil code is properly formatted'
runs:
  using: composite
  steps:
    # since this job runs on its own virtual machine, we need to get the dependencies (which may be cached for us)
    - name: Get Core Dependencies
      uses: ./.github/workflows/actions/get-core-dependencies

    - name: Prettier Check
      run: npm run prettier.dry-run
      shell: bash

