triage:
  label: "holiday triage"
  dryRun: false

comment:
  labels:
    - label: "holiday triage"
      message: >
        Thanks for the issue! This issue has been labeled as `holiday triage`. With the winter holidays quickly approaching, much of the Stencil Team will soon be taking time off. During this time, issue triaging and PR review will be delayed until the team begins to return. After this period, we will work to ensure that all new issues are properly triaged and that new PRs are reviewed.
        
        In the meantime, please read our [Winter Holiday Triage Guide](https://github.com/ionic-team/stencil/issues/3186) for information on how to ensure that your issue is triaged correctly.
        
        Thank you!
        
closeAndLock:
  labels:
    - label: "ionitron: support"
      message: >
        Thanks for the issue! This issue appears to be a support request. We use this issue tracker exclusively for
        bug reports and feature requests. Please use our [slack channel](https://stencil-worldwide.herokuapp.com/)
        for questions about Stencil.


        Thank you for using Stencil!
    - label: "ionitron: missing template"
      message: >
        Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
        template in order to gather more information and further assist you. Please create a new issue and ensure the
        template is fully filled out.


        Thank you for using Stencil!
  close: true
  lock: true
  dryRun: false

noReply:
  maxIssuesPerRun: 100
  includePullRequests: false
  label: Awaiting Reply
  responseLabel: Reply Received
  close: false
  lock: false
  dryRun: false

stale:
  days: 180
  maxIssuesPerRun: 100
  exemptLabels:
    - good first issue
    - help wanted
    - Reply Received
    - triage
  exemptAssigned: true
  exemptProjects: true
  exemptMilestones: true
  label: "ionitron: stale issue"
  message: >
    Thanks for the issue! This issue is being closed due to inactivity. If this is still
    an issue with the latest version of Stencil, please create a new issue and ensure the
    template is fully filled out.


    Thank you for using Stencil!
  close: true
  lock: true
  dryRun: false

wrongRepo:
  repos:
    - label: "ionitron: cli"
      repo: ionic-cli
      message: >
        Thanks for the issue! We use this issue tracker exclusively for bug reports and feature requests
        associated with Stencil. It appears that this issue is associated with the Ionic CLI.
        I am moving this issue to the Ionic CLI repository. Please track this issue over there.


        Thank you for using Stencil!
    - label: "ionitron: ionic"
      repo: ionic
      message: >
        Thanks for the issue! We use this issue tracker exclusively for bug reports and feature requests
        associated with Stencil. It appears that this issue is associated with the Ionic Framework.
        I am moving this issue to the Ionic Framework repository. Please track this issue over there.


        Thank you for using Stencil!
  close: true
  lock: true
  dryRun: false
