/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CmpA {}
  interface CmpB {}
  interface CmpC {}
}

declare global {


  interface HTMLCmpAElement extends Components.CmpA, HTMLStencilElement {}
  var HTMLCmpAElement: {
    prototype: HTMLCmpAElement;
    new (): HTMLCmpAElement;
  };

  interface HTMLCmpBElement extends Components.CmpB, HTMLStencilElement {}
  var HTMLCmpBElement: {
    prototype: HTMLCmpBElement;
    new (): HTMLCmpBElement;
  };

  interface HTMLCmpCElement extends Components.CmpC, HTMLStencilElement {}
  var HTMLCmpCElement: {
    prototype: HTMLCmpCElement;
    new (): HTMLCmpCElement;
  };
  interface HTMLElementTagNameMap {
    'cmp-a': HTMLCmpAElement;
    'cmp-b': HTMLCmpBElement;
    'cmp-c': HTMLCmpCElement;
  }
}

declare namespace LocalJSX {
  interface CmpA extends JSXBase.HTMLAttributes<HTMLCmpAElement> {}
  interface CmpB extends JSXBase.HTMLAttributes<HTMLCmpBElement> {}
  interface CmpC extends JSXBase.HTMLAttributes<HTMLCmpCElement> {}

  interface IntrinsicElements {
    'cmp-a': CmpA;
    'cmp-b': CmpB;
    'cmp-c': CmpC;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


