/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface SiblingRoot {

    }
  }

  interface HTMLSiblingRootElement extends StencilComponents.SiblingRoot, HTMLStencilElement {}

  var HTMLSiblingRootElement: {
    prototype: HTMLSiblingRootElement;
    new (): HTMLSiblingRootElement;
  };
  interface HTMLElementTagNameMap {
    'sibling-root': HTMLSiblingRootElement;
  }
  interface ElementTagNameMap {
    'sibling-root': HTMLSiblingRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sibling-root': JSXElements.SiblingRootAttributes;
    }
  }
  namespace JSXElements {
    export interface SiblingRootAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
