/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface SiblingRoot {

    }
  }


    interface HTMLSiblingRootElement extends StencilComponents.SiblingRoot, HTMLStencilElement {}

    var HTMLSiblingRootElement: {
      prototype: HTMLSiblingRootElement;
      new (): HTMLSiblingRootElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'sibling-root': JSXElements.SiblingRootAttributes;
    }
  }

  namespace JSXElements {

    export interface SiblingRootAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'sibling-root': HTMLSiblingRootElement
  }

  interface ElementTagNameMap {
    'sibling-root': HTMLSiblingRootElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

