var SiteMenu = /** @class */ (function () {
    function SiteMenu() {
    }
    SiteMenu.prototype.render = function () {
        return (h("div", 0,
            h("ul", 0,
                h("li", 0,
                    h("h4", 0, t("Introduction")),
                    h("ul", 0,
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/intro" } }, t("What is Stencil?"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/getting-started" } }, t("Getting Started"))))),
                h("li", 0,
                    h("h4", 0, t("Basics")),
                    h("ul", 0,
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/my-first-component" } }, t("My First Component"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/templating" } }, t("Templating"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/decorators" } }, t("Decorators"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/events" } }, t("Events"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/component-lifecycle" } }, t("Component Life Cycle"))))),
                h("li", 0,
                    h("h4", 0, t("Advanced")),
                    h("ul", 0,
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/stencil-config" } }, t("Stencil Configuration"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/prerendering" } }, t("Prerendering"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/server-side-rendering" } }, t("Server Side Rendering"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/service-workers" } }, t("Service Workers"))),
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/distribution" } }, t("Distribution"))))),
                h("li", 0,
                    h("h4", 0, t("Add-ons")),
                    h("ul", 0,
                        h("li", 0,
                            h("stencil-route-link", { "a": { "url": "/docs/routing" } }, t("Router"))))),
                h("li", 0,
                    h("h4", 0, t("Community")),
                    h("ul", 0,
                        h("li", 0,
                            h("a", { "a": { "href": "https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM", "title": "Stencil slack channel" } }, t("Stencil Slack"))),
                        h("li", 0,
                            h("a", { "a": { "href": "https://twitter.com/stenciljs" } }, t("Stencil on Twitter"))))))));
    };
    return SiteMenu;
}());
export { SiteMenu };
