(function(){
/*
Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var eb="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
(function(){function k(){var a=this;this.m={};this.g=document.documentElement;var b=new pa;b.rules=[];this.h=t.set(this.g,new t(b));this.i=!1;this.a=this.b=null;fb(function(){a.c()})}function D(){this.customStyles=[];this.enqueued=!1}function gb(){}function ba(a){this.cache={};this.f=void 0===a?100:a}function n(){}function t(a,b,c,d,e){this.F=a||null;this.b=b||null;this.pa=c||[];this.M=null;this.U=e||"";this.a=this.C=this.G=null}function q(){}function pa(){this.end=this.start=0;this.rules=this.parent=
this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}function Ic(a){function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;l(this)&&(e=[],K(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var g=e[f];1===g.__CE_state&&a.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?a.c(this):a.j(this);
return b}})}function c(b,c){x(b,"insertAdjacentElement",function(b,d){var e=l(d);b=c.call(this,b,d);e&&a.a(d);l(b)&&a.b(d);return b})}hb?x(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=hb.call(this,a)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(qa&&qa.get)b(Element.prototype,qa);else if(ra&&ra.get)b(HTMLElement.prototype,ra);else{var d=sa.call(document,"div");a.o(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return ib.call(this,
!0).innerHTML},set:function(a){var b="template"===this.localName?this.content:this;for(d.innerHTML=a;0<b.childNodes.length;)ta.call(b,b.childNodes[0]);for(;0<d.childNodes.length;)da.call(b,d.childNodes[0])}})})}x(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return jb.call(this,b,c);var d=ua.call(this,b);jb.call(this,b,c);c=ua.call(this,b);d!==c&&a.attributeChangedCallback(this,b,d,c,null)});x(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return kb.call(this,
b,c,d);var e=ea.call(this,b,c);kb.call(this,b,c,d);d=ea.call(this,b,c);e!==d&&a.attributeChangedCallback(this,c,e,d,b)});x(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return lb.call(this,b);var c=ua.call(this,b);lb.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});x(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return mb.call(this,b,c);var d=ea.call(this,b,c);mb.call(this,b,c);var e=ea.call(this,b,c);d!==e&&a.attributeChangedCallback(this,
c,d,e,b)});nb?c(HTMLElement.prototype,nb):ob?c(Element.prototype,ob):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");pb(a,Element.prototype,{Ca:Jc,append:Kc});Lc(a,{Sa:Mc,Ra:Nc,ab:Oc,remove:Pc})}function Lc(a,b){var c=Element.prototype;c.before=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&l(a)});b.Sa.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(l(this))for(f=0;f<d.length;f++)g=d[f],
g instanceof Element&&a.b(g)};c.after=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&l(a)});b.Ra.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(l(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};c.replaceWith=function(c){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];var f=d.filter(function(a){return a instanceof Node&&l(a)}),g=l(this);b.ab.apply(this,d);for(var h=0;h<f.length;h++)a.a(f[h]);
if(g)for(a.a(this),f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};c.remove=function(){var c=l(this);b.remove.call(this);c&&a.a(this)}}function Qc(a){function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&l(this))for(var c=Array(h),m=0;m<h;m++)c[m]=e[m]}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)a.a(c[b])}}})}
x(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=qb.call(this,b,d);if(l(this))for(d=0;d<c.length;d++)a.b(c[d]);return b}c=l(b);d=qb.call(this,b,d);c&&a.a(b);l(this)&&a.b(b);return d});x(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=da.call(this,b);if(l(this))for(var e=0;e<c.length;e++)a.b(c[e]);return b}c=l(b);e=da.call(this,b);c&&a.a(b);l(this)&&
a.b(b);return e});x(Node.prototype,"cloneNode",function(b){b=ib.call(this,b);this.ownerDocument.__CE_hasRegistry?a.c(b):a.j(b);return b});x(Node.prototype,"removeChild",function(b){var c=l(b),e=ta.call(this,b);c&&a.a(b);return e});x(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=rb.call(this,b,d);if(l(this))for(a.a(d),d=0;d<c.length;d++)a.b(c[d]);return b}var c=l(b),f=rb.call(this,b,d),g=l(this);g&&a.a(d);c&&a.a(b);g&&
a.b(b);return f});va&&va.get?b(Node.prototype,va):a.o(function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)ta.call(this,this.firstChild);da.call(this,document.createTextNode(a))}})})}function Rc(a){x(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.f(b);if(c)return new c.constructor}b=sa.call(this,b);a.g(b);return b});
x(Document.prototype,"importNode",function(b,c){b=Sc.call(this,b,c);this.__CE_hasRegistry?a.c(b):a.j(b);return b});x(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.f(c);if(d)return new d.constructor}b=Tc.call(this,b,c);a.g(b);return b});pb(a,Document.prototype,{Ca:Uc,append:Vc})}function pb(a,b,c){b.prepend=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof
Node&&l(a)});c.Ca.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(l(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)};b.append=function(b){for(var d=[],f=0;f<arguments.length;++f)d[f-0]=arguments[f];f=d.filter(function(a){return a instanceof Node&&l(a)});c.append.apply(this,d);for(var g=0;g<f.length;g++)a.a(f[g]);if(l(this))for(f=0;f<d.length;f++)g=d[f],g instanceof Element&&a.b(g)}}function Wc(a){window.HTMLElement=function(){function b(){var b=this.constructor,d=a.H(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");
var e=d.constructionStack;if(!e.length)return e=sa.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.g(e),e;var d=e.length-1,f=e[d];if(f===sb)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");e[d]=sb;Object.setPrototypeOf(f,b.prototype);a.g(f);return f}b.prototype=Xc.prototype;return b}()}function w(a){this.f=!1;this.a=a;this.h=new Map;this.g=function(a){return a()};this.b=!1;this.c=
[];this.j=new wa(a,document)}function tb(){var a=this;this.b=this.a=void 0;this.f=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function wa(a,b){this.b=a;this.a=b;this.J=void 0;this.b.c(this.a);"loading"===this.a.readyState&&(this.J=new MutationObserver(this.f.bind(this)),this.J.observe(this.a,{childList:!0,subtree:!0}))}function y(){this.m=new Map;this.l=new Map;this.i=[];this.h=!1}function p(a,b){if(a!==ub)throw new TypeError("Illegal constructor");a=document.createDocumentFragment();a.__proto__=
p.prototype;a.i(b);return a}function z(a){this.root=a;this.Z="slot"}function P(a){if(!a.__shady||void 0===a.__shady.firstChild){a.__shady=a.__shady||{};a.__shady.firstChild=xa(a);a.__shady.lastChild=ya(a);vb(a);for(var b=a.__shady.childNodes=W(a),c=0,d;c<b.length&&(d=b[c]);c++)d.__shady=d.__shady||{},d.__shady.parentNode=a,d.__shady.nextSibling=b[c+1]||null,d.__shady.previousSibling=b[c-1]||null,wb(d)}}function Yc(a){var b=a&&a.J;b&&(b.Y.delete(a.Oa),b.Y.size||(a.Pa.__shady.S=null))}function Zc(a,
b){a.__shady=a.__shady||{};a.__shady.S||(a.__shady.S=new fa);a.__shady.S.Y.add(b);var c=a.__shady.S;return{Oa:b,J:c,Pa:a,takeRecords:function(){return c.takeRecords()}}}function fa(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.Y=new Set}function E(a){return"ShadyRoot"===a.Ma}function Q(a){a=a.getRootNode();if(E(a))return a}function za(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,
e,f)}}function xb(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)za(a,c[d]);return a}function $c(a,b){for(var c in b)a[c]=b[c]}function yb(a){Aa.push(a);Ba.textContent=zb++}function Ab(a){Ca||(Ca=!0,yb(Da));X.push(a)}function Da(){Ca=!1;for(var a=!!X.length;X.length;)X.shift()();return a}function ad(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===
a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})}function Bb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Cb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}function Ea(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){var h;
a:{var m;h=g;m=a;var k=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var ca=h.localName,l="<"+ca,n=h.attributes,p=0;m=n[p];p++)l+=" "+m.name+'="'+m.value.replace(bd,Bb)+'"';l+=">";h=cd[ca]?l:l+Ea(h,k)+"</"+ca+">";break a;case Node.TEXT_NODE:h=h.data;h=m&&dd[m.localName]?h:h.replace(ed,Bb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),Error("not implemented");}}c+=h}return c}function L(a){A.currentNode=a;return A.parentNode()}function xa(a){A.currentNode=
a;return A.firstChild()}function ya(a){A.currentNode=a;return A.lastChild()}function Db(a){A.currentNode=a;return A.previousSibling()}function Eb(a){A.currentNode=a;return A.nextSibling()}function W(a){var b=[];A.currentNode=a;for(a=A.firstChild();a;)b.push(a),a=A.nextSibling();return b}function Fb(a){B.currentNode=a;return B.parentNode()}function Gb(a){B.currentNode=a;return B.firstChild()}function Hb(a){B.currentNode=a;return B.lastChild()}function Ib(a){B.currentNode=a;return B.previousSibling()}
function Jb(a){B.currentNode=a;return B.nextSibling()}function Kb(a){var b=[];B.currentNode=a;for(a=B.firstChild();a;)b.push(a),a=B.nextSibling();return b}function Lb(a){return Ea(a,function(a){return W(a)})}function Mb(a){if(a.nodeType!==Node.ELEMENT_NODE)return a.nodeValue;a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b}function I(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,
d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function M(a){I(a,Nb);I(a,Fa);I(a,Ga)}function Ob(a,b,c){wb(a);c=c||null;a.__shady=a.__shady||{};b.__shady=b.__shady||{};c&&(c.__shady=c.__shady||{});a.__shady.previousSibling=c?c.__shady.previousSibling:b.lastChild;var d=a.__shady.previousSibling;d&&d.__shady&&(d.__shady.nextSibling=a);(d=a.__shady.nextSibling=c)&&d.__shady&&(d.__shady.previousSibling=a);a.__shady.parentNode=b;c?c===b.__shady.firstChild&&(b.__shady.firstChild=a):(b.__shady.lastChild=
a,b.__shady.firstChild||(b.__shady.firstChild=a));b.__shady.childNodes=null}function Pb(a){var b=a.__shady&&a.__shady.parentNode,c,d=Q(a);if(b||d){c=Qb(a);if(b){a.__shady=a.__shady||{};b.__shady=b.__shady||{};a===b.__shady.firstChild&&(b.__shady.firstChild=a.__shady.nextSibling);a===b.__shady.lastChild&&(b.__shady.lastChild=a.__shady.previousSibling);var e=a.__shady.previousSibling,f=a.__shady.nextSibling;e&&(e.__shady=e.__shady||{},e.__shady.nextSibling=f);f&&(f.__shady=f.__shady||{},f.__shady.previousSibling=
e);a.__shady.parentNode=a.__shady.previousSibling=a.__shady.nextSibling=void 0;void 0!==b.__shady.childNodes&&(b.__shady.childNodes=null)}if(e=d){for(var g,e=d.ka(),f=0;f<e.length;f++){var h=e[f],m;a:{for(m=h;m;){if(m==a){m=!0;break a}m=m.parentNode}m=void 0}if(m)for(h=h.assignedNodes({flatten:!0}),m=0;m<h.length;m++){g=!0;var k=h[m],l=L(k);l&&R.call(l,k)}}e=g}b=b&&d&&b.localName===d.w.Z;if(e||b)d.W=!1,ga(d)}Ha(a);return c}function Ia(a,b,c){if(a=a.__shady&&a.__shady.S)b&&a.addedNodes.push(b),c&&
a.removedNodes.push(c),a.cb()}function Ja(a){if(a&&a.nodeType){a.__shady=a.__shady||{};var b=a.__shady.qa;void 0===b&&(E(a)?b=a:b=(b=a.parentNode)?Ja(b):a,document.documentElement.contains(a)&&(a.__shady.qa=b));return b}}function Rb(a,b,c){var d,e=c.w.Z;if(a.nodeType!==Node.DOCUMENT_FRAGMENT_NODE||a.__noInsertionPoint)a.localName===e&&(P(b),P(a),d=!0);else for(var e=a.querySelectorAll(e),f=0,g,h;f<e.length&&(g=e[f]);f++)h=g.parentNode,h===a&&(h=b),h=Rb(g,h,c),d=d||h;return d}function Sb(a){return(a=
a&&a.__shady&&a.__shady.root)&&a.na()}function Ha(a){if(a.__shady&&void 0!==a.__shady.qa)for(var b=a.childNodes,c=0,d=b.length,e;c<d&&(e=b[c]);c++)Ha(e);a.__shady=a.__shady||{};a.__shady.qa=void 0}function Qb(a){a=a.parentNode;if(Sb(a))return ga(a.__shady.root),!0}function ga(a){a.ja=!0;a.update()}function Tb(a,b){"slot"===b?Qb(a):"slot"===a.localName&&"name"===b&&(a=Q(a))&&a.update()}function Ub(a,b,c){var d=[];Vb(a.childNodes,b,c,d);return d}function Vb(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=
a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var m=b,k=c,l=d,n=m(h);n&&l.push(h);k&&k(n)?h=n:(Vb(h.childNodes,m,k,l),h=void 0)}if(h)break}}function Wb(a){a=a.getRootNode();E(a)&&a.Da()}function Xb(a,b,c){if(c){var d=c.__shady&&c.__shady.parentNode;if(void 0!==d&&d!==a||void 0===d&&L(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.nodeType!==Node.DOCUMENT_FRAGMENT_NODE&&
((d=b.__shady&&b.__shady.parentNode)?(Ia(d,null,b),Pb(b)):(b.parentNode&&R.call(b.parentNode,b),Ha(b)));var d=c,e=Q(a),f;e&&(b.__noInsertionPoint&&!e.ja&&(e.W=!0),f=Rb(b,a,e))&&(e.W=!1);if(a.__shady&&void 0!==a.__shady.firstChild)if(vb(a),a.__shady=a.__shady||{},void 0!==a.__shady.firstChild&&(a.__shady.childNodes=null),b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){for(var g=b.childNodes,h=0;h<g.length;h++)Ob(g[h],a,d);b.__shady=b.__shady||{};g=void 0!==b.__shady.firstChild?null:void 0;b.__shady.firstChild=
b.__shady.lastChild=g;b.__shady.childNodes=g}else Ob(b,a,d);var g=f,h=e&&e.w.Z||"",m=b.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&!b.__noInsertionPoint&&h&&b.querySelector(h);f=m&&m.parentNode.nodeType!==Node.DOCUMENT_FRAGMENT_NODE;((m=m||b.localName===h)||a.localName===h||g)&&e&&ga(e);(e=Sb(a))&&ga(a.__shady&&a.__shady.root);if(!(e||m&&!f||a.__shady.root||d&&E(d.parentNode)&&d.parentNode.K)){if(c&&(d=Q(c))){var k;if(c.localName===d.w.Z)a:{d=c.assignedNodes({flatten:!0});e=Ja(c);f=0;for(g=d.length;f<
g&&(k=d[f]);f++)if(e.$(c,k))break a;k=void 0}else k=c;c=k}k=E(a)?a.host:a;c?Ka.call(k,b,c):Yb.call(k,b)}Ia(a,b);return b}function Zb(a,b){if(a.ownerDocument!==document)return La.call(document,a,b);var c=La.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Zb(a[b],!0),c.appendChild(d)}return c}function Ma(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;
c[c.length-1]===document&&c.push(window);return c}function $b(a,b){if(!E)return a;a=Ma(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!E(f)||-1<g)return d}function Na(a){function b(b,d){b=new a(b,d);b.ha=d&&!!d.composed;return b}$c(b,a);b.prototype=a.prototype;return b}function ac(a,b,c){if(c=b.v&&b.v[a.type]&&b.v[a.type][c])for(var d=0,e;(e=c[d])&&(e.call(b,a),!a.Ka);d++);}function fd(a){var b=a.composedPath(),c;Object.defineProperty(a,
"currentTarget",{get:function(){return c},configurable:!0});for(var d=b.length-1;0<=d;d--)if(c=b[d],ac(a,c,"capture"),a.ia)return;Object.defineProperty(a,"eventPhase",{value:Event.AT_TARGET});for(var e,d=0;d<b.length;d++)if(c=b[d],!d||c.shadowRoot&&c.shadowRoot===e)if(ac(a,c,"bubble"),c!==window&&(e=c.getRootNode()),a.ia)break}function bc(a,b,c,d,e,f){var g=a.type,h=a.capture,m=a.once,k=a.passive;return b===a.node&&c===g&&d===h&&e===m&&f===k}function gd(){for(var a in Oa)window.addEventListener(a,
function(a){a.__target||(cc(a),fd(a))},!0)}function cc(a){a.__target=a.target;a.ta=a.relatedTarget;if(C.R){var b=dc,c=Object.getPrototypeOf(a);if(!c.hasOwnProperty("__patchProto")){var d=Object.create(c);d.ib=c;za(d,b);c.__patchProto=d}a.__proto__=c.__patchProto}else za(a,dc)}function Y(a,b){return{index:a,T:[],X:b}}function hd(a,b,c,d){var e=0,f=0,g=0,h=0,m=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<m;g++)if(a[g]!==c[g])break a;g=m}if(b==a.length&&d==c.length){for(var h=a.length,k=c.length,l=0;l<
m-g&&id(a[--h],c[--k]);)l++;h=l}e+=g;f+=g;b-=h;d-=h;if(!(b-e||d-f))return[];if(e==b){for(b=Y(e,0);f<d;)b.T.push(c[f++]);return[b]}if(f==d)return[Y(e,b-e)];m=e;g=f;d=d-g+1;h=b-m+1;b=Array(d);for(k=0;k<d;k++)b[k]=Array(h),b[k][0]=k;for(k=0;k<h;k++)b[0][k]=k;for(k=1;k<d;k++)for(l=1;l<h;l++)if(a[m+l-1]===c[g+k-1])b[k][l]=b[k-1][l-1];else{var n=b[k-1][l]+1,p=b[k][l-1]+1;b[k][l]=n<p?n:p}m=b.length-1;g=b[0].length-1;d=b[m][g];for(a=[];0<m||0<g;)m?g?(h=b[m-1][g-1],k=b[m-1][g],l=b[m][g-1],n=k<l?k<h?k:h:l<
h?l:h,n==h?(h==d?a.push(0):(a.push(1),d=h),m--,g--):n==k?(a.push(3),m--,d=k):(a.push(2),g--,d=l)):(a.push(3),m--):(a.push(2),g--);a.reverse();b=void 0;m=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(m.push(b),b=void 0);e++;f++;break;case 1:b||(b=Y(e,0));b.X++;e++;b.T.push(c[f]);f++;break;case 2:b||(b=Y(e,0));b.X++;e++;break;case 3:b||(b=Y(e,0)),b.T.push(c[f]),f++}b&&m.push(b);return m}function id(a,b){return a===b}function ec(a){Wb(a);return a.__shady&&a.__shady.assignedSlot||null}function S(a,
b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}}function fc(a){var b=jd.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function l(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function Pa(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}function K(a,b,c){c=c?c:new Set;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)K(d,b,c);d=Pa(a,e);continue}else if("template"===f){d=Pa(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)K(e,b,c)}d=d.firstChild?
d.firstChild:Pa(a,d)}}function x(a,b,c){a[b]=c}function Qa(a){a=a.replace(F.Ua,"").replace(F.port,"");var b=gc,c=a,d=new pa;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null,e=new pa;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}function gc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&((c=b.substring(a.previous?
a.previous.end:a.parent.start,a.start-1),c=kd(c),c=c.replace(F.Ba," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=!c.indexOf("@"),a.atRule)?c.indexOf("@media")?c.match(F.Za)&&(a.type=H.ga,a.keyframesName=a.selector.split(F.Ba).pop()):a.type=H.MEDIA_RULE:a.type=c.indexOf("--")?H.STYLE_RULE:H.ra);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)gc(f,b);return a}function kd(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a=
"0"+a;return"\\"+a})}function hc(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=hc(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(F.wa,"").replace(F.Aa,""),b=b.replace(F.$a,"").replace(F.fb,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}function ic(a){a&&(v=v&&!a.nativeCss&&!a.shimcssproperties,
u=u&&!a.nativeShadow&&!a.shimshadow)}function T(a,b){if(!a)return"";"string"===typeof a&&(a=Qa(a));b&&U(a,b);return hc(a,v)}function ha(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Qa(a.textContent));return a.__cssRules||null}function jc(a){return!!a.parent&&a.parent.type===H.ga}function U(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===H.MEDIA_RULE){var g=a.selector.match(ld);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===H.STYLE_RULE?b(a):c&&f===H.ga?c(a):f===H.ra&&(e=!0);if((a=a.rules)&&!e)for(var e=
0,f=a.length,h;e<f&&(h=a[e]);e++)U(h,b,c,d)}}function Ra(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;kc(e,c,d);return e}function kc(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);N?a.compareDocumentPosition(N)===Node.DOCUMENT_POSITION_PRECEDING&&(N=a):N=a}function lc(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d;a:{var e=0;d=c+3;for(var f=a.length;d<f;d++)if("("===a[d])e++;else if(")"===a[d]&&!--e)break a;
d=-1}e=a.substring(c+4,d);c=a.substring(0,c);a=lc(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function ia(a,b){u?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}function O(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,U:c}}function md(a){(a=ja[a])&&(a._applyShimInvalid=!0)}function nd(a){a.a||(a.a=
!0,od.then(function(){a._applyShimInvalid=!1;a.a=!1}))}function fb(a){mc?mc(a):(Sa||(Sa=new Promise(function(a){Ta=a}),"complete"===document.readyState?Ta():document.addEventListener("readystatechange",function(){"complete"===document.readyState&&Ta()})),Sa.then(function(){a&&a()}))}var C=window.ShadyDOM||{};C.Wa=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var Ua=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");C.R=!!(Ua&&Ua.configurable&&Ua.get);C.za=C.force||!C.Wa;
var V=Element.prototype,nc=V.matches||V.matchesSelector||V.mozMatchesSelector||V.msMatchesSelector||V.oMatchesSelector||V.webkitMatchesSelector,Ba=document.createTextNode(""),zb=0,Aa=[];(new MutationObserver(function(){for(;Aa.length;)try{Aa.shift()()}catch(a){throw Ba.textContent=zb++,a;}})).observe(Ba,{characterData:!0});var X=[],Ca;Da.list=X;fa.prototype.cb=function(){var a=this;this.a||(this.a=!0,yb(function(){a.b()}))};fa.prototype.b=function(){if(this.a){this.a=!1;var a=this.takeRecords();a.length&&
this.Y.forEach(function(b){b(a)})}};fa.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};var Yb=Element.prototype.appendChild,Ka=Element.prototype.insertBefore,R=Element.prototype.removeChild,oc=Element.prototype.setAttribute,pc=Element.prototype.removeAttribute,Va=Element.prototype.cloneNode,La=Document.prototype.importNode,qc=Element.prototype.addEventListener,
rc=Element.prototype.removeEventListener,pd=Object.freeze({appendChild:Yb,insertBefore:Ka,removeChild:R,setAttribute:oc,removeAttribute:pc,cloneNode:Va,importNode:La,addEventListener:qc,removeEventListener:rc}),bd=/[&\u00A0"]/g,ed=/[&\u00A0<>]/g,cd=Cb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),dd=Cb("style script xmp iframe noembed noframes plaintext noscript".split(" ")),A=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),B=document.createTreeWalker(document,
NodeFilter.SHOW_ELEMENT,null,!1),qd=Object.freeze({parentNode:L,firstChild:xa,lastChild:ya,previousSibling:Db,nextSibling:Eb,childNodes:W,parentElement:Fb,firstElementChild:Gb,lastElementChild:Hb,previousElementSibling:Ib,nextElementSibling:Jb,children:Kb,innerHTML:Lb,textContent:Mb}),Wa=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML")||Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML"),ka=document.implementation.createHTMLDocument("inert").createElement("div"),Xa=Object.getOwnPropertyDescriptor(Document.prototype,
"activeElement"),Nb={parentElement:{get:function(){var a=this.__shady&&this.__shady.parentElement;return void 0!==a?a:Fb(this)},configurable:!0},parentNode:{get:function(){var a=this.__shady&&this.__shady.parentNode;return void 0!==a?a:L(this)},configurable:!0},nextSibling:{get:function(){var a=this.__shady&&this.__shady.nextSibling;return void 0!==a?a:Eb(this)},configurable:!0},previousSibling:{get:function(){var a=this.__shady&&this.__shady.previousSibling;return void 0!==a?a:Db(this)},configurable:!0},
className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0},nextElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.nextSibling){for(var a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return Jb(this)},configurable:!0},previousElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.previousSibling){for(var a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;
return a}return Ib(this)},configurable:!0}},Fa={childNodes:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){if(!this.__shady.childNodes){this.__shady.childNodes=[];for(var a=this.firstChild;a;a=a.nextSibling)this.__shady.childNodes.push(a)}return this.__shady.childNodes}return W(this)},configurable:!0},firstChild:{get:function(){var a=this.__shady&&this.__shady.firstChild;return void 0!==a?a:xa(this)},configurable:!0},lastChild:{get:function(){var a=this.__shady&&this.__shady.lastChild;
return void 0!==a?a:ya(this)},configurable:!0},textContent:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.textContent);return a.join("")}return Mb(this)},set:function(a){if(this.nodeType!==Node.ELEMENT_NODE)this.nodeValue=a;else{for(;this.firstChild;)this.removeChild(this.firstChild);a&&this.appendChild(document.createTextNode(a))}},configurable:!0},firstElementChild:{get:function(){if(this.__shady&&
void 0!==this.__shady.firstChild){for(var a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return Gb(this)},configurable:!0},lastElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.lastChild){for(var a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return Hb(this)},configurable:!0},children:{get:function(){return this.__shady&&void 0!==this.__shady.firstChild?Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===
Node.ELEMENT_NODE}):Kb(this)},configurable:!0},innerHTML:{get:function(){var a="template"===this.localName?this.content:this;return this.__shady&&void 0!==this.__shady.firstChild?Ea(a):Lb(a)},set:function(a){for(var b="template"===this.localName?this.content:this;b.firstChild;)b.removeChild(b.firstChild);for(Wa&&Wa.set?Wa.set.call(ka,a):ka.innerHTML=a;ka.firstChild;)b.appendChild(ka.firstChild)},configurable:!0}},sc={shadowRoot:{get:function(){return this.__shady&&this.__shady.root||null},set:function(a){this.__shady=
this.__shady||{};this.__shady.root=a},configurable:!0}},Ga={activeElement:{get:function(){var a;a=Xa&&Xa.get?Xa.get.call(document):C.R?void 0:document.activeElement;if(a&&a.nodeType){var b=!!E(this);if(this===document||b&&this.host!==a&&this.host.contains(a)){for(b=Q(a);b&&b!==this;)a=b.host,b=Q(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}},wb=C.R?function(){}:function(a){a.__shady&&a.__shady.Na||(a.__shady=a.__shady||{},a.__shady.Na=
!0,I(a,Nb,!0))},vb=C.R?function(){}:function(a){a.__shady&&a.__shady.La||(a.__shady=a.__shady||{},a.__shady.La=!0,I(a,Fa,!0),I(a,sc,!0))},la=null,rd={focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,
pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},dc={get composed(){!1!==this.isTrusted&&void 0===this.ha&&(this.ha=rd[this.type]);return this.ha||!1},composedPath:function(){this.sa||(this.sa=Ma(this.__target,this.composed));return this.sa},get target(){return $b(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.ta)return null;
this.ua||(this.ua=Ma(this.ta,!0));return $b(this.currentTarget,this.ua)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.ia=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.ia=this.Ka=!0}},Oa={focus:!0,blur:!0},sd=Na(window.Event),td=Na(window.CustomEvent),ud=Na(window.MouseEvent),vd="function"===typeof Event?Event:function(a,b){b=b||{};var c=document.createEvent("Event");c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};
z.prototype.Va=function(){return this.root.querySelectorAll("slot")};z.prototype.oa=function(a){return a.localName&&"slot"==a.localName};z.prototype.ma=function(){return this.root.na()?this.g(this.c()):[]};z.prototype.c=function(){for(var a=[],b=0,c=this.root.host.firstChild;c;c=c.nextSibling)a[b++]=c;return a};z.prototype.g=function(a){for(var b=[],c=this.root.ka(),d=0,e=c.length,f;d<e&&(f=c[d]);d++){this.f(f,a);var g=f.parentNode;(g=g&&g.__shady&&g.__shady.root)&&g.na()&&b.push(g)}for(c=0;c<a.length;c++)if(d=
a[c])d.__shady=d.__shady||{},d.__shady.assignedSlot=void 0,(e=L(d))&&R.call(e,d);return b};z.prototype.f=function(a,b){var c=a.__shady.assignedNodes;c&&this.va(a,!0);a.__shady.assignedNodes=[];for(var d=!1,e=!1,f=0,g=b.length,h;f<g;f++)(h=b[f])&&this.h(h,a)&&(h.__shady.la!=a&&(d=!0),this.b(h,a),b[f]=void 0,e=!0);if(!e)for(b=a.childNodes,e=0;e<b.length;e++)h=b[e],h.__shady.la!=a&&(d=!0),this.b(h,a);if(c){for(h=0;h<c.length;h++)c[h].__shady.la=null;a.__shady.assignedNodes.length<c.length&&(d=!0)}this.i(a);
d&&this.a(a)};z.prototype.va=function(a,b){var c=a.__shady.assignedNodes;if(c)for(var d=0;d<c.length;d++){var e=c[d];b&&(e.__shady.la=e.__shady.assignedSlot);e.__shady.assignedSlot===a&&(e.__shady.assignedSlot=null)}};z.prototype.h=function(a,b){b=(b=b.getAttribute("name"))?b.trim():"";a=(a=a.getAttribute&&a.getAttribute("slot"))?a.trim():"";return a==b};z.prototype.b=function(a,b){b.__shady.assignedNodes.push(a);a.__shady.assignedSlot=b};z.prototype.i=function(a){var b=a.__shady.assignedNodes;a.__shady.L=
[];for(var c=0,d;c<b.length&&(d=b[c]);c++)if(this.oa(d)){var e=d.__shady.L;if(e)for(var f=0;f<e.length;f++)a.__shady.L.push(e[f])}else a.__shady.L.push(b[c])};z.prototype.a=function(a){a.dispatchEvent(new vd("slotchange"));a.__shady.assignedSlot&&this.a(a.__shady.assignedSlot)};z.prototype.$=function(a){return!a.__shady.assignedSlot};var ub={};p.prototype=Object.create(DocumentFragment.prototype);p.prototype.i=function(a){this.Ma="ShadyRoot";P(a);P(this);a.shadowRoot=this;this.host=a;this.ja=this.K=
!1;this.w=new z(this);this.update()};p.prototype.update=function(){var a=this;this.K||(this.K=!0,Ab(function(){return a.Da()}))};p.prototype.h=function(){for(var a=this,b=this;b;)b.K&&(a=b),b=b.Qa();return a};p.prototype.Qa=function(){var a=this.host.getRootNode();if(E(a))for(var b=this.host.childNodes,c=0,d;c<b.length;c++)if(d=b[c],this.w.oa(d))return a};p.prototype.Da=function(){this.K&&this.h()._render()};p.prototype._render=function(){this.ja=this.K=!1;this.W||this.f();this.W=!1;this.ma();this.j()};
p.prototype.ma=function(){for(var a=this.w.ma(),b=0;b<a.length;b++)a[b]._render()};p.prototype.f=function(){var a=this.a;if(a)for(var b=0,c;b<a.length;b++)c=a[b],c.getRootNode()!==this&&this.w.va(c);a=this.a=this.w.Va();for(b=0;b<a.length;b++)c=a[b],c.__shady=c.__shady||{},P(c),P(c.parentNode)};p.prototype.j=function(){this.g()};p.prototype.g=function(){this.c(this.host,this.b(this.host));for(var a=this.ka(),b=0,c=a.length,d,e;b<c&&(d=a[b]);b++)e=d.parentNode,e!==this.host&&e!==this&&this.c(e,this.b(e))};
p.prototype.b=function(a){var b=[];a=(a.__shady&&a.__shady.root||a).childNodes;for(var c=0;c<a.length;c++){var d=a[c];if(this.w.oa(d))for(var e=d.__shady.L||(d.__shady.L=[]),f=0;f<e.length;f++){var g=e[f];this.$(d,g)&&b.push(g)}else b.push(d)}return b};p.prototype.$=function(a,b){return this.w.$(a,b)};p.prototype.c=function(a,b){for(var c=W(a),d=hd(b,b.length,c,c.length),e=0,f=0,g;e<d.length&&(g=d[e]);e++){for(var h=0,k;h<g.T.length&&(k=g.T[h]);h++)L(k)===a&&R.call(a,k),c.splice(g.index+f,1);f-=g.X}for(e=
0;e<d.length&&(g=d[e]);e++)for(f=c[g.index],h=g.index;h<g.index+g.X;h++)k=b[h],Ka.call(a,k,f),c.splice(h,0,k)};p.prototype.na=function(){return!(!this.a||!this.a.length)};p.prototype.ka=function(){this.a||this.f();return this.a};(function(a){I(a,Fa,!0);I(a,Ga,!0)})(p.prototype);var wd={addEventListener:function(a,b,c){if(b){var d,e,f;"object"===typeof c?(d=!!c.capture,e=!!c.once,f=!!c.passive):(d=!!c,f=e=!1);if(b.u)for(var g=0;g<b.u.length;g++){if(bc(b.u[g],this,a,d,e,f))return}else b.u=[];g=function(d){e&&
this.removeEventListener(a,b,c);d.__target||cc(d);if(d.composed||-1<d.composedPath().indexOf(this))if(d.eventPhase===Event.BUBBLING_PHASE&&d.target===d.relatedTarget)d.stopImmediatePropagation();else return b.call(this,d)};b.u.push({node:this,type:a,capture:d,once:e,passive:f,gb:g});Oa[a]?(this.v=this.v||{},this.v[a]=this.v[a]||{capture:[],bubble:[]},this.v[a][d?"capture":"bubble"].push(g)):qc.call(this,a,g,c)}},removeEventListener:function(a,b,c){if(b){var d,e,f;"object"===typeof c?(d=!!c.capture,
e=!!c.once,f=!!c.passive):(d=!!c,f=e=!1);var g=void 0;if(b.u)for(var h=0;h<b.u.length;h++)if(bc(b.u[h],this,a,d,e,f)){g=b.u.splice(h,1)[0].gb;b.u.length||(b.u=void 0);break}rc.call(this,a,g||b,c);g&&Oa[a]&&this.v&&this.v[a]&&(a=this.v[a][d?"capture":"bubble"],g=a.indexOf(g),-1<g&&a.splice(g,1))}},appendChild:function(a){return Xb(this,a)},insertBefore:function(a,b){return Xb(this,a,b)},removeChild:function(a){if(a.parentNode!==this)throw Error("The node to be removed is not a child of this node: "+
a);if(!Pb(a)){var b=E(this)?this.host:this,c=L(a);b===c&&R.call(b,a)}Ia(this,null,a);return a},replaceChild:function(a,b){this.insertBefore(a,b);this.removeChild(b);return a},cloneNode:function(a){var b;if("template"==this.localName)b=Va.call(this,a);else if(b=Va.call(this,!1),a){a=this.childNodes;for(var c=0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Ja(this)},get isConnected(){var a=this.ownerDocument;if(a&&a.contains&&a.contains(this)||(a=a.documentElement)&&
a.contains&&a.contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(a instanceof p?a.host:void 0);return!!(a&&a instanceof Document)}},xd={get assignedSlot(){return ec(this)}},Ya={querySelector:function(a){return Ub(this,function(b){return nc.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a){return Ub(this,function(b){return nc.call(b,a)})}},tc={assignedNodes:function(a){if("slot"===this.localName)return Wb(this),this.__shady?(a&&a.flatten?this.__shady.L:
this.__shady.assignedNodes)||[]:[]}},uc=xb({setAttribute:function(a,b){la||(la=window.ShadyCSS&&window.ShadyCSS.ScopingShim);la&&"class"===a?la.setElementClass(this,b):(oc.call(this,a,b),Tb(this,a))},removeAttribute:function(a){pc.call(this,a);Tb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new p(ub,this)},get slot(){return this.getAttribute("slot")},set slot(a){this.setAttribute("slot",a)},get assignedSlot(){return ec(this)}},Ya,
tc);Object.defineProperties(uc,sc);var vc=xb({importNode:function(a,b){return Zb(a,b)}},Ya);Object.defineProperties(vc,{_activeElement:Ga.activeElement});C.za&&(window.ShadyDOM={inUse:C.za,patch:function(a){return a},isShadyRoot:E,enqueue:Ab,flush:Da,settings:C,filterMutations:ad,observeChildren:Zc,unobserveChildren:Yc,nativeMethods:pd,nativeTree:qd},window.Event=sd,window.CustomEvent=td,window.MouseEvent=ud,gd(),S(window.Node.prototype,wd),S(window.Text.prototype,xd),S(window.DocumentFragment.prototype,
Ya),S(window.Element.prototype,uc),S(window.Document.prototype,vc),window.HTMLSlotElement&&S(window.HTMLSlotElement.prototype,tc),C.R&&(M(window.Node.prototype),M(window.Text.prototype),M(window.DocumentFragment.prototype),M(window.Element.prototype),M((window.customElements&&window.customElements.nativeHTMLElement||HTMLElement).prototype),M(window.Document.prototype),window.HTMLSlotElement&&M(window.HTMLSlotElement.prototype)),window.ShadowRoot=p);var jd=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));
y.prototype.I=function(a,b){this.m.set(a,b);this.l.set(b.constructor,b)};y.prototype.f=function(a){return this.m.get(a)};y.prototype.H=function(a){return this.l.get(a)};y.prototype.o=function(a){this.h=!0;this.i.push(a)};y.prototype.j=function(a){var b=this;this.h&&K(a,function(a){return b.g(a)})};y.prototype.g=function(a){if(this.h&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.i.length;b++)this.i[b](a)}};y.prototype.b=function(a){var b=[];K(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=
b[a];1===c.__CE_state?this.connectedCallback(c):this.B(c)}};y.prototype.a=function(a){var b=[];K(a,function(a){return b.push(a)});for(a=0;a<b.length;a++){var c=b[a];1===c.__CE_state&&this.disconnectedCallback(c)}};y.prototype.c=function(a,b){b=b?b:new Set;var c=this,d=[];K(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var e=a.import;e instanceof Node&&"complete"===e.readyState?(e.__CE_isImportDocument=!0,e.__CE_hasRegistry=!0):a.addEventListener("load",function(){var d=
a.import;d.__CE_documentLoadHandled||(d.__CE_documentLoadHandled=!0,d.__CE_isImportDocument=!0,d.__CE_hasRegistry=!0,new Set(b),b.delete(d),c.c(d,b))})}else d.push(a)},b);if(this.h)for(a=0;a<d.length;a++)this.g(d[a]);for(a=0;a<d.length;a++)this.B(d[a])};y.prototype.B=function(a){if(void 0===a.__CE_state){var b=this.f(a.localName);if(b){b.constructionStack.push(a);var c=b.constructor;try{try{if(new c!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{b.constructionStack.pop()}}catch(f){throw a.__CE_state=
2,f;}a.__CE_state=1;a.__CE_definition=b;if(b.attributeChangedCallback)for(b=b.observedAttributes,c=0;c<b.length;c++){var d=b[c],e=a.getAttribute(d);null!==e&&this.attributeChangedCallback(a,d,null,e,null)}l(a)&&this.connectedCallback(a)}}};y.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};y.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};y.prototype.attributeChangedCallback=
function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};wa.prototype.c=function(){this.J&&this.J.disconnect()};wa.prototype.f=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||this.c();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)this.b.c(c[d])};tb.prototype.c=function(){if(this.a)throw Error("Already resolved.");this.a=void 0;this.b&&this.b(void 0)};w.prototype.i=
function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!fc(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.a.f(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.f)throw Error("A custom element is already being defined.");this.f=!0;var d,e,f,g,h;try{var k=function(a){var b=l[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");
return b},l=b.prototype;if(!(l instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");d=k("connectedCallback");e=k("disconnectedCallback");f=k("adoptedCallback");g=k("attributeChangedCallback");h=b.observedAttributes||[]}catch(ca){return}finally{this.f=!1}this.a.I(a,{localName:a,constructor:b,connectedCallback:d,disconnectedCallback:e,adoptedCallback:f,attributeChangedCallback:g,observedAttributes:h,constructionStack:[]});this.c.push(a);this.b||(this.b=
!0,this.g(function(){return c.l()}))};w.prototype.l=function(){if(!1!==this.b)for(this.b=!1,this.a.c(document);0<this.c.length;){var a=this.c.shift();(a=this.h.get(a))&&a.c()}};w.prototype.get=function(a){if(a=this.a.f(a))return a.constructor};w.prototype.o=function(a){if(!fc(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.h.get(a);if(b)return b.f;b=new tb;this.h.set(a,b);this.a.f(a)&&-1===this.c.indexOf(a)&&b.c();return b.f};w.prototype.m=function(a){this.j.c();
var b=this.g;this.g=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=w;w.prototype.define=w.prototype.i;w.prototype.get=w.prototype.get;w.prototype.whenDefined=w.prototype.o;w.prototype.polyfillWrapFlushCallback=w.prototype.m;var sa=window.Document.prototype.createElement,Tc=window.Document.prototype.createElementNS,Sc=window.Document.prototype.importNode,Uc=window.Document.prototype.prepend,Vc=window.Document.prototype.append,ib=window.Node.prototype.cloneNode,da=window.Node.prototype.appendChild,
qb=window.Node.prototype.insertBefore,ta=window.Node.prototype.removeChild,rb=window.Node.prototype.replaceChild,va=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),hb=window.Element.prototype.attachShadow,qa=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),ua=window.Element.prototype.getAttribute,jb=window.Element.prototype.setAttribute,lb=window.Element.prototype.removeAttribute,ea=window.Element.prototype.getAttributeNS,kb=window.Element.prototype.setAttributeNS,
mb=window.Element.prototype.removeAttributeNS,ob=window.Element.prototype.insertAdjacentElement,Jc=window.Element.prototype.prepend,Kc=window.Element.prototype.append,Mc=window.Element.prototype.before,Nc=window.Element.prototype.after,Oc=window.Element.prototype.replaceWith,Pc=window.Element.prototype.remove,Xc=window.HTMLElement,ra=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),nb=window.HTMLElement.prototype.insertAdjacentElement,sb=new function(){},ma=window.customElements;
if(!ma||ma.forcePolyfill||"function"!=typeof ma.define||"function"!=typeof ma.get){var Z=new y;Wc(Z);Rc(Z);Qc(Z);Ic(Z);document.__CE_hasRegistry=!0;var yd=new w(Z);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:yd})}var H={STYLE_RULE:1,ga:7,MEDIA_RULE:4,ra:1E3},F={Ua:/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,port:/@import[^;]*;/gim,wa:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Aa:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,$a:/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,
fb:/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Za:/^@[^\s]*keyframes/,Ba:/\s+/g},u=!(window.ShadyDOM&&window.ShadyDOM.inUse),v=!navigator.userAgent.match("AppleWebKit/601")&&window.CSS&&CSS.supports&&CSS.supports("box-shadow","0 0 0 var(--foo)");window.ShadyCSS?ic(window.ShadyCSS):window.WebComponents&&ic(window.WebComponents.flags);var wc=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:([^;{]*)|{([^}]*)})(?:(?=[;\s}])|$)/gi,xc=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,zd=/(--[\w-]+)\s*([:,;)]|$)/gi,Ad=/(animation\s*:)|(animation-name\s*:)/,
ld=/@media[^(]*(\([^)]*\))/,Bd=/\{[^}]*\}/g,N=null;q.prototype.g=function(a,b,c){a.__styleScoped?a.__styleScoped=null:this.i(a,b||"",c)};q.prototype.i=function(a,b,c){a.nodeType===Node.ELEMENT_NODE&&this.B(a,b,c);if(a="template"===a.localName?(a.content||a.jb).childNodes:a.children||a.childNodes)for(var d=0;d<a.length;d++)this.i(a[d],b,c)};q.prototype.B=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));
else if(a.getAttribute){var d=a.getAttribute(Cd);c?d&&(b=d.replace("style-scope","").replace(b,""),ia(a,b)):ia(a,(d?d+" ":"")+"style-scope "+b)}};q.prototype.b=function(a,b,c){var d=a.__cssBuild;u||"shady"===d?b=T(b,c):(a=O(a),b=this.N(b,a.is,a.U,c)+"\n\n");return b.trim()};q.prototype.N=function(a,b,c,d){var e=this.c(b,c);b=this.h(b);var f=this;return T(a,function(a){a.c||(f.P(a,b,e),a.c=!0);d&&d(a,b,e)})};q.prototype.h=function(a){return a?Dd+a:""};q.prototype.c=function(a,b){return b?"[is="+a+
"]":a};q.prototype.P=function(a,b,c){this.j(a,this.f,b,c)};q.prototype.j=function(a,b,c,d){a.selector=a.A=this.l(a,b,c,d)};q.prototype.l=function(a,b,c,d){var e=a.selector.split(yc);if(!jc(a)){a=0;for(var f=e.length,g;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.join(yc)};q.prototype.f=function(a,b,c){var d=this,e=!1;a=a.trim();a=a.replace(Ed,function(a,b,d){return":"+b+"("+d.replace(/\s/g,"")+")"});a=a.replace(Fd,Za+" $1");return a=a.replace(Gd,function(a,g,h){e||(a=d.H(h,g,b,c),e=e||a.stop,
g=a.Ta,h=a.value);return g+h})};q.prototype.H=function(a,b,c,d){var e=a.indexOf($a);0<=a.indexOf(Za)?a=this.V(a,d):0!==e&&(a=c?this.m(a,c):a);c=!1;0<=e&&(b="",c=!0);var f;c&&(f=!0,c&&(a=a.replace(Hd,function(a,b){return" > "+b})));a=a.replace(Id,function(a,b,d){return'[dir="'+d+'"] '+b+", "+b+'[dir="'+d+'"]'});return{value:a,Ta:b,stop:f}};q.prototype.m=function(a,b){a=a.split(zc);a[0]+=b;return a.join(zc)};q.prototype.V=function(a,b){var c=a.match(Ac);return(c=c&&c[2].trim()||"")?c[0].match(Bc)?a.replace(Ac,
function(a,c,f){return b+f}):c.split(Bc)[0]===b?c:Jd:a.replace(Za,b)};q.prototype.O=function(a){a.selector=a.parsedSelector;this.o(a);this.j(a,this.I)};q.prototype.o=function(a){a.selector===Kd&&(a.selector="html")};q.prototype.I=function(a){return a.match($a)?this.f(a,Cc):this.m(a.trim(),Cc)};eb.Object.defineProperties(q.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});var Ed=/:(nth[-\w]+)\(([^)]+)\)/,Cc=":not(.style-scope)",yc=",",Gd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=\[])+)/g,
Bc=/[[.:#*]/,Za=":host",Kd=":root",$a="::slotted",Fd=new RegExp("^("+$a+")"),Ac=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Hd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Id=/(.*):dir\((?:(ltr|rtl))\)/,Dd=".",zc=":",Cd="class",Jd="should_not_match",r=new q;t.get=function(a){return a?a.__styleInfo:null};t.set=function(a,b){return a.__styleInfo=b};t.prototype.c=function(){return this.F};t.prototype._getStyleRules=t.prototype.c;var Dc=function(a){return a.matches||a.matchesSelector||a.mozMatchesSelector||
a.msMatchesSelector||a.oMatchesSelector||a.webkitMatchesSelector}(window.Element.prototype),Ld=navigator.userAgent.match("Trident");n.prototype.P=function(a){var b=this,c={},d=[],e=0;U(a,function(a){b.c(a);a.index=e++;b.O(a.s.cssText,c)},function(a){d.push(a)});a.b=d;a=[];for(var f in c)a.push(f);return a};n.prototype.c=function(a){if(!a.s){var b={},c={};this.b(a,c)&&(b.D=c,a.rules=null);b.cssText=this.N(a);a.s=b}};n.prototype.b=function(a,b){var c=a.s;if(c){if(c.D)return Object.assign(b,c.D),!0}else{for(var c=
a.parsedCssText,d;a=wc.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}};n.prototype.N=function(a){return this.V(a.parsedCssText)};n.prototype.V=function(a){return a.replace(Bd,"").replace(wc,"")};n.prototype.O=function(a,b){for(var c;c=zd.exec(a);){var d=c[1];":"!==c[2]&&(b[d]=!0)}};n.prototype.da=function(a){for(var b=Object.getOwnPropertyNames(a),c=0,d;c<b.length;c++)d=b[c],a[d]=this.a(a[d],a)};n.prototype.a=function(a,b){if(a)if(0<=a.indexOf(";"))a=
this.f(a,b);else{var c=this;a=lc(a,function(a,e,f,g){if(!e)return a+g;(e=c.a(b[e],b))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=c.a(b[f]||f,b)||f;return a+(e||"")+g})}return a&&a.trim()||""};n.prototype.f=function(a,b){a=a.split(";");for(var c=0,d,e;c<a.length;c++)if(d=a[c]){xc.lastIndex=0;if(e=xc.exec(d))d=this.a(b[e[1]],b);else if(e=d.indexOf(":"),-1!==e){var f=d.substring(e),f=f.trim(),f=this.a(f,b)||f;d=d.substring(0,e)+f}a[c]=d&&d.lastIndexOf(";")===d.length-1?d.slice(0,-1):d||
""}return a.join(";")};n.prototype.I=function(a,b){var c="";a.s||this.c(a);a.s.cssText&&(c=this.f(a.s.cssText,b));a.cssText=c};n.prototype.H=function(a,b){var c=a.cssText,d=a.cssText;null==a.ya&&(a.ya=Ad.test(c));if(a.ya)if(null==a.aa){a.aa=[];for(var e in b)d=b[e],d=d(c),c!==d&&(c=d,a.aa.push(e))}else{for(e=0;e<a.aa.length;++e)d=b[a.aa[e]],c=d(c);d=c}a.cssText=d};n.prototype.ca=function(a,b){var c={},d=this,e=[];U(a,function(a){a.s||d.c(a);var f=a.A||a.parsedSelector;b&&a.s.D&&f&&Dc.call(b,f)&&(d.b(a,
c),a=a.index,f=parseInt(a/32,10),e[f]=(e[f]||0)|1<<a%32)},null,!0);return{D:c,key:e}};n.prototype.fa=function(a,b,c,d){b.s||this.c(b);if(b.s.D){var e=O(a);a=e.is;var e=e.U,e=a?r.c(a,e):"html",f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(u&&!b.A&&(b.A=r.l(b,r.f,r.h(a),e)),c=b.A||e),d({eb:c,Ya:h,lb:g})}};n.prototype.ba=
function(a,b){var c={},d={},e=this,f=b&&b.__cssBuild;U(b,function(b){e.fa(a,b,f,function(f){Dc.call(a.kb||a,f.eb)&&(f.Ya?e.b(b,c):e.b(b,d))})},null,!0);return{bb:d,Xa:c}};n.prototype.ea=function(a,b,c){var d=this,e=O(a),f=r.c(e.is,e.U),g=new RegExp("(?:^|[^.#[:])"+(a.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),e=t.get(a).F,h=this.h(e,c);return r.b(a,e,function(a){d.I(a,b);u||jc(a)||!a.cssText||(d.H(a,h),d.l(a,g,f,c))})};n.prototype.h=function(a,b){a=a.b;var c={};if(!u&&a)for(var d=0,e=
a[d];d<a.length;e=a[++d])this.j(e,b),c[e.keyframesName]=this.i(e);return c};n.prototype.i=function(a){return function(b){return b.replace(a.f,a.a)}};n.prototype.j=function(a,b){a.f=new RegExp(a.keyframesName,"g");a.a=a.keyframesName+"-"+b;a.A=a.A||a.selector;a.selector=a.A.replace(a.keyframesName,a.a)};n.prototype.l=function(a,b,c,d){a.A=a.A||a.selector;d="."+d;for(var e=a.A.split(","),f=0,g=e.length,h;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};n.prototype.o=
function(a,b,c){var d=a.getAttribute("class")||"",e=d;c&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+c+"\\s*","g")," "));e+=(e?" ":"")+"x-scope "+b;d!==e&&ia(a,e)};n.prototype.B=function(a,b,c,d){b=d?d.textContent||"":this.ea(a,b,c);var e=t.get(a),f=e.a;f&&!u&&f!==d&&(f._useCount--,0>=f._useCount&&f.parentNode&&f.parentNode.removeChild(f));u?e.a?(e.a.textContent=b,d=e.a):b&&(d=Ra(b,c,a.shadowRoot,e.b)):d?d.parentNode||kc(d,null,e.b):b&&(d=Ra(b,c,null,e.b));d&&(d._useCount=d._useCount||0,e.a!=d&&d._useCount++,
e.a=d);Ld&&(d.textContent=d.textContent);return d};n.prototype.m=function(a,b){var c=ha(a),d=this;a.textContent=T(c,function(a){var c=a.cssText=a.parsedCssText;a.s&&a.s.cssText&&(c=c.replace(F.wa,"").replace(F.Aa,""),a.cssText=d.f(c,b))})};eb.Object.defineProperties(n.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var J=new n,ab={},na=window.customElements;if(na&&!u){var Md=na.define;na.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+
" "),e=document.head;e.insertBefore(d,(N?N.nextSibling:null)||e.firstChild);N=d;ab[a]=d;return Md.call(na,a,b,c)}}ba.prototype.b=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.D[e]!==b[e])return!1}return!0};ba.prototype.c=function(a,b,c,d){var e=this.cache[a]||[];e.push({D:b,styleElement:c,C:d});e.length>this.f&&e.shift();this.cache[a]=e};ba.prototype.a=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.b(e,b,c))return e}};if(!u){var Ec=function(a){for(var b=
0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head){for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.classList&&!e.classList.contains(r.a)||e instanceof window.SVGElement&&(!e.hasAttribute("class")||0>e.getAttribute("class").indexOf(r.a))){var f=e.getRootNode();f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(f=f.host)&&(f=O(f).is,r.g(e,f))}}for(d=0;d<c.removedNodes.length;d++)if(e=c.removedNodes[d],e.nodeType===Node.ELEMENT_NODE&&(f=void 0,e.classList?
f=Array.from(e.classList):e.hasAttribute("class")&&(f=e.getAttribute("class").split(/\s+/)),f)){var g=f.indexOf(r.a);0<=g&&(f=f[g+1])&&r.g(e,f,!0)}}}},Fc=new MutationObserver(Ec),Gc=function(a){Fc.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.flush)Gc(document);else{var bb=function(){Gc(document.body)};window.HTMLImports?window.HTMLImports.whenReady(bb):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){bb();document.removeEventListener("readystatechange",
a)};document.addEventListener("readystatechange",a)}else bb()})}gb=function(){Ec(Fc.takeRecords())}}var ja={},od=Promise.resolve(),Sa=null,mc=window.HTMLImports&&window.HTMLImports.whenReady||null,Ta,oa=null,aa=null;D.prototype.xa=function(){!this.enqueued&&aa&&(this.enqueued=!0,fb(aa))};D.prototype.b=function(a){a.__seenByShadyCSS||(a.__seenByShadyCSS=!0,this.customStyles.push(a),this.xa())};D.prototype.a=function(a){return a.__shadyCSSCachedStyle?a.__shadyCSSCachedStyle:a.getStyle?a.getStyle():
a};D.prototype.c=function(){for(var a=this.customStyles,b=0;b<a.length;b++){var c=a[b];if(!c.__shadyCSSCachedStyle){var d=this.a(c);if(d){var e=d.__appliedElement;if(e)for(var f=0;f<d.attributes.length;f++){var g=d.attributes[f];e.setAttribute(g.name,g.value)}d=e||d;oa&&oa(d);c.__shadyCSSCachedStyle=d}}}return a};D.prototype.addCustomStyle=D.prototype.b;D.prototype.getStyleForCustomStyle=D.prototype.a;D.prototype.processStyles=D.prototype.c;Object.defineProperties(D.prototype,{transformCallback:{get:function(){return oa},
set:function(a){oa=a}},validateCallback:{get:function(){return aa},set:function(a){var b=!1;aa||(b=!0);aa=a;b&&this.xa()}}});var Hc=new ba;k.prototype.H=function(){gb()};k.prototype.ba=function(a){var b=this.m[a]=(this.m[a]||0)+1;return a+"-"+b};k.prototype.Ha=function(a){return ha(a)};k.prototype.Ja=function(a){return T(a)};k.prototype.P=function(a){a=a.content.querySelectorAll("style");for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push(d.textContent);d.parentNode.removeChild(d)}return b.join("").trim()};
k.prototype.da=function(a){return(a=a.content.querySelector("style"))?a.getAttribute("css-build")||"":""};k.prototype.prepareTemplate=function(a,b,c){if(!a.f){a.f=!0;a.name=b;a.extends=c;ja[b]=a;var d=this.da(a),e=this.P(a);c={is:b,extends:c,hb:d};u||r.g(a.content,b);this.c();var f=this.b.detectMixin(e),e=Qa(e);f&&v&&this.b.transformRules(e,b);a._styleAst=e;a.g=d;d=[];v||(d=J.P(a._styleAst));if(!d.length||v)b=this.ca(c,a._styleAst,u?a.content:null,ab[b]),a.b=b;a.c=d}};k.prototype.ca=function(a,b,
c,d){b=r.b(a,b);if(b.length)return Ra(b,a.is,c,d)};k.prototype.fa=function(a){var b=O(a),c=b.is,b=b.U,d=ab[c],c=ja[c],e,f;c&&(e=c._styleAst,f=c.c);return t.set(a,new t(e,d,f,0,b))};k.prototype.N=function(){if(!this.b)if(window.ShadyCSS.ApplyShim)this.b=window.ShadyCSS.ApplyShim,this.b.invalidCallback=md;else{var a={};this.b=(a.detectMixin=function(){return!1},a.transformRule=function(){},a.transformRules=function(){},a)}};k.prototype.O=function(){var a=this;if(!this.a)if(window.ShadyCSS.CustomStyleInterface)this.a=
window.ShadyCSS.CustomStyleInterface,this.a.transformCallback=function(b){a.B(b)},this.a.validateCallback=function(){requestAnimationFrame(function(){(a.a.enqueued||a.i)&&a.f()})};else{var b={};this.a=(b.processStyles=function(){},b.enqueued=!1,b.getStyleForCustomStyle=function(){return null},b)}};k.prototype.c=function(){this.N();this.O()};k.prototype.f=function(){this.c();var a=this.a.processStyles();this.a.enqueued&&(v?this.Fa(a):(this.o(this.g,this.h),this.I(a)),this.a.enqueued=!1,this.i&&!v&&
this.styleDocument())};k.prototype.styleElement=function(a,b){var c=O(a).is,d=t.get(a);d||(d=this.fa(a));this.j(a)||(this.i=!0);b&&(d.M=d.M||{},Object.assign(d.M,b));if(v){if(d.M){b=d.M;for(var e in b)null===e?a.style.removeProperty(e):a.style.setProperty(e,b[e])}((e=ja[c])||this.j(a))&&e&&e.b&&e._applyShimInvalid&&(e.a||(this.c(),this.b.transformRules(e._styleAst,c),e.b.textContent=r.b(a,d.F),nd(e)),u&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=r.b(a,d.F)),d.F=e._styleAst)}else this.o(a,
d),d.pa&&d.pa.length&&this.V(a,d)};k.prototype.l=function(a){return(a=a.getRootNode().host)?t.get(a)?a:this.l(a):this.g};k.prototype.j=function(a){return a===this.g};k.prototype.V=function(a,b){var c=O(a).is,d=Hc.a(c,b.G,b.pa),e=d?d.styleElement:null,f=b.C;b.C=d&&d.C||this.ba(c);e=J.B(a,b.G,b.C,e);u||J.o(a,b.C,f);d||Hc.c(c,b.G,e,b.C)};k.prototype.o=function(a,b){var c=this.l(a),d=t.get(c),c=Object.create(d.G||null),e=J.ba(a,b.F);a=J.ca(d.F,a).D;Object.assign(c,e.Xa,a,e.bb);this.ea(c,b.M);J.da(c);
b.G=c};k.prototype.ea=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};k.prototype.styleDocument=function(a){this.styleSubtree(this.g,a)};k.prototype.styleSubtree=function(a,b){var c=a.shadowRoot;(c||this.j(a))&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};k.prototype.Fa=function(a){for(var b=0;b<a.length;b++){var c=this.a.getStyleForCustomStyle(a[b]);
c&&this.Ea(c)}};k.prototype.I=function(a){for(var b=0;b<a.length;b++){var c=this.a.getStyleForCustomStyle(a[b]);c&&J.m(c,this.h.G)}};k.prototype.B=function(a){var b=this,c=ha(a);U(c,function(a){u?r.o(a):r.O(a);v&&(b.c(),b.b.transformRule(a))});v?a.textContent=T(c):this.h.F.rules.push(c)};k.prototype.Ea=function(a){if(v){var b=ha(a);this.c();this.b.transformRules(b);a.textContent=T(b)}};k.prototype.getComputedStyleValue=function(a,b){var c;v||(c=(t.get(a)||t.get(this.l(a))).G[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?
c.trim():""};k.prototype.Ia=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d)for(var d=d.split(/\s/),e=0;e<d.length;e++)if(d[e]===r.a){c=d[e+1];break}}c&&b.push(r.a,c);v||(c=t.get(a))&&c.C&&b.push(J.g,c.C);ia(a,b.join(" "))};k.prototype.Ga=function(a){return t.get(a)};k.prototype.flush=k.prototype.H;k.prototype.prepareTemplate=k.prototype.prepareTemplate;k.prototype.styleElement=k.prototype.styleElement;k.prototype.styleDocument=
k.prototype.styleDocument;k.prototype.styleSubtree=k.prototype.styleSubtree;k.prototype.getComputedStyleValue=k.prototype.getComputedStyleValue;k.prototype.setElementClass=k.prototype.Ia;k.prototype._styleInfoForNode=k.prototype.Ga;k.prototype.transformCustomStyleForDocument=k.prototype.B;k.prototype.getStyleAst=k.prototype.Ha;k.prototype.styleAstToString=k.prototype.Ja;k.prototype.flushCustomStyles=k.prototype.f;Object.defineProperties(k.prototype,{nativeShadow:{get:function(){return u}},nativeCss:{get:function(){return v}}});
var G=new k,cb,db;window.ShadyCSS&&(cb=window.ShadyCSS.ApplyShim,db=window.ShadyCSS.CustomStyleInterface);window.ShadyCSS={ScopingShim:G,prepareTemplate:function(a,b,c){G.f();G.prepareTemplate(a,b,c)},styleSubtree:function(a,b){G.f();G.styleSubtree(a,b)},styleElement:function(a){G.f();G.styleElement(a)},styleDocument:function(a){G.f();G.styleDocument(a)},getComputedStyleValue:function(a,b){return G.getComputedStyleValue(a,b)},nativeCss:v,nativeShadow:u};cb&&(window.ShadyCSS.ApplyShim=cb);db&&(window.ShadyCSS.CustomStyleInterface=
db);requestAnimationFrame(function(){window.dispatchEvent(new CustomEvent("WebComponentsReady"))})})();
}).call(self)
