/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface AppRoot {

    }

    interface CurrentDate {

    }
  }


    interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

    var HTMLAppRootElement: {
      prototype: HTMLAppRootElement;
      new (): HTMLAppRootElement;
    };
    

    interface HTMLCurrentDateElement extends StencilComponents.CurrentDate, HTMLStencilElement {}

    var HTMLCurrentDateElement: {
      prototype: HTMLCurrentDateElement;
      new (): HTMLCurrentDateElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'app-root': JSXElements.AppRootAttributes;
    'current-date': JSXElements.CurrentDateAttributes;
    }
  }

  namespace JSXElements {

    export interface AppRootAttributes extends HTMLAttributes {

    }

    export interface CurrentDateAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'current-date': HTMLCurrentDateElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'current-date': HTMLCurrentDateElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

