import { Context, setMode } from '@stencil/core/internal/client';
export { setAssetPath, setNonce, setPlatformOptions } from '@stencil/core/internal/client';
export { AppendChild, defineCustomElement as defineCustomElementAppendChild } from './append-child.js';
export { AttributeBasic, defineCustomElement as defineCustomElementAttributeBasic } from './attribute-basic.js';
export { AttributeBasicRoot, defineCustomElement as defineCustomElementAttributeBasicRoot } from './attribute-basic-root.js';
export { AttributeBoolean, defineCustomElement as defineCustomElementAttributeBoolean } from './attribute-boolean.js';
export { AttributeBooleanRoot, defineCustomElement as defineCustomElementAttributeBooleanRoot } from './attribute-boolean-root.js';
export { AttributeComplex, defineCustomElement as defineCustomElementAttributeComplex } from './attribute-complex.js';
export { AttributeHost, defineCustomElement as defineCustomElementAttributeHost } from './attribute-host.js';
export { AttributeHtmlRoot, defineCustomElement as defineCustomElementAttributeHtmlRoot } from './attribute-html-root.js';
export { BadSharedJsx, defineCustomElement as defineCustomElementBadSharedJsx } from './bad-shared-jsx.js';
export { BuildData, defineCustomElement as defineCustomElementBuildData } from './build-data.js';
export { ChildReflectNanAttribute, defineCustomElement as defineCustomElementChildReflectNanAttribute } from './child-reflect-nan-attribute.js';
export { ChildWithReflection, defineCustomElement as defineCustomElementChildWithReflection } from './child-with-reflection.js';
export { CmpLabel, defineCustomElement as defineCustomElementCmpLabel } from './cmp-label.js';
export { CmpLabelWithSlotSibling, defineCustomElement as defineCustomElementCmpLabelWithSlotSibling } from './cmp-label-with-slot-sibling.js';
export { ConditionalBasic, defineCustomElement as defineCustomElementConditionalBasic } from './conditional-basic.js';
export { ConditionalRerender, defineCustomElement as defineCustomElementConditionalRerender } from './conditional-rerender.js';
export { ConditionalRerenderRoot, defineCustomElement as defineCustomElementConditionalRerenderRoot } from './conditional-rerender-root.js';
export { CssCmp, defineCustomElement as defineCustomElementCssCmp } from './css-cmp.js';
export { CssVariablesNoEncapsulation, defineCustomElement as defineCustomElementCssVariablesNoEncapsulation } from './css-variables-no-encapsulation.js';
export { CssVariablesShadowDom, defineCustomElement as defineCustomElementCssVariablesShadowDom } from './css-variables-shadow-dom.js';
export { CustomElementChild, defineCustomElement as defineCustomElementCustomElementChild } from './custom-element-child.js';
export { CustomElementChildDifferentNameThanClass, defineCustomElement as defineCustomElementCustomElementChildDifferentNameThanClass } from './custom-element-child-different-name-than-class.js';
export { CustomElementNestedChild, defineCustomElement as defineCustomElementCustomElementNestedChild } from './custom-element-nested-child.js';
export { CustomElementRoot, defineCustomElement as defineCustomElementCustomElementRoot } from './custom-element-root.js';
export { CustomElementRootDifferentNameThanClass, defineCustomElement as defineCustomElementCustomElementRootDifferentNameThanClass } from './custom-element-root-different-name-than-class.js';
export { CustomElementsDelegatesFocus, defineCustomElement as defineCustomElementCustomElementsDelegatesFocus } from './custom-elements-delegates-focus.js';
export { CustomElementsNoDelegatesFocus, defineCustomElement as defineCustomElementCustomElementsNoDelegatesFocus } from './custom-elements-no-delegates-focus.js';
export { CustomEventRoot, defineCustomElement as defineCustomElementCustomEventRoot } from './custom-event-root.js';
export { DelegatesFocus, defineCustomElement as defineCustomElementDelegatesFocus } from './delegates-focus.js';
export { DomReattach, defineCustomElement as defineCustomElementDomReattach } from './dom-reattach.js';
export { DomReattachClone, defineCustomElement as defineCustomElementDomReattachClone } from './dom-reattach-clone.js';
export { DomReattachCloneDeepSlot, defineCustomElement as defineCustomElementDomReattachCloneDeepSlot } from './dom-reattach-clone-deep-slot.js';
export { DomReattachCloneHost, defineCustomElement as defineCustomElementDomReattachCloneHost } from './dom-reattach-clone-host.js';
export { DynamicCssVariable, defineCustomElement as defineCustomElementDynamicCssVariable } from './dynamic-css-variable.js';
export { DynamicImport, defineCustomElement as defineCustomElementDynamicImport } from './dynamic-import.js';
export { Es5AddclassSvg, defineCustomElement as defineCustomElementEs5AddclassSvg } from './es5-addclass-svg.js';
export { EsmImport, defineCustomElement as defineCustomElementEsmImport } from './esm-import.js';
export { EventBasic, defineCustomElement as defineCustomElementEventBasic } from './event-basic.js';
export { EventCustomType, defineCustomElement as defineCustomElementEventCustomType } from './event-custom-type.js';
export { ExternalImportA, defineCustomElement as defineCustomElementExternalImportA } from './external-import-a.js';
export { ExternalImportB, defineCustomElement as defineCustomElementExternalImportB } from './external-import-b.js';
export { ExternalImportC, defineCustomElement as defineCustomElementExternalImportC } from './external-import-c.js';
export { FactoryJsx, defineCustomElement as defineCustomElementFactoryJsx } from './factory-jsx.js';
export { ImageImport, defineCustomElement as defineCustomElementImageImport } from './image-import.js';
export { InitCssRoot, defineCustomElement as defineCustomElementInitCssRoot } from './init-css-root.js';
export { InputBasicRoot, defineCustomElement as defineCustomElementInputBasicRoot } from './input-basic-root.js';
export { JsonBasic, defineCustomElement as defineCustomElementJsonBasic } from './json-basic.js';
export { KeyReorder, defineCustomElement as defineCustomElementKeyReorder } from './key-reorder.js';
export { KeyReorderRoot, defineCustomElement as defineCustomElementKeyReorderRoot } from './key-reorder-root.js';
export { LifecycleAsyncA, defineCustomElement as defineCustomElementLifecycleAsyncA } from './lifecycle-async-a.js';
export { LifecycleAsyncB, defineCustomElement as defineCustomElementLifecycleAsyncB } from './lifecycle-async-b.js';
export { LifecycleAsyncC, defineCustomElement as defineCustomElementLifecycleAsyncC } from './lifecycle-async-c.js';
export { LifecycleBasicA, defineCustomElement as defineCustomElementLifecycleBasicA } from './lifecycle-basic-a.js';
export { LifecycleBasicB, defineCustomElement as defineCustomElementLifecycleBasicB } from './lifecycle-basic-b.js';
export { LifecycleBasicC, defineCustomElement as defineCustomElementLifecycleBasicC } from './lifecycle-basic-c.js';
export { LifecycleNestedA, defineCustomElement as defineCustomElementLifecycleNestedA } from './lifecycle-nested-a.js';
export { LifecycleNestedB, defineCustomElement as defineCustomElementLifecycleNestedB } from './lifecycle-nested-b.js';
export { LifecycleNestedC, defineCustomElement as defineCustomElementLifecycleNestedC } from './lifecycle-nested-c.js';
export { LifecycleUnloadA, defineCustomElement as defineCustomElementLifecycleUnloadA } from './lifecycle-unload-a.js';
export { LifecycleUnloadB, defineCustomElement as defineCustomElementLifecycleUnloadB } from './lifecycle-unload-b.js';
export { LifecycleUnloadRoot, defineCustomElement as defineCustomElementLifecycleUnloadRoot } from './lifecycle-unload-root.js';
export { LifecycleUpdateA, defineCustomElement as defineCustomElementLifecycleUpdateA } from './lifecycle-update-a.js';
export { LifecycleUpdateB, defineCustomElement as defineCustomElementLifecycleUpdateB } from './lifecycle-update-b.js';
export { LifecycleUpdateC, defineCustomElement as defineCustomElementLifecycleUpdateC } from './lifecycle-update-c.js';
export { ListenJsx, defineCustomElement as defineCustomElementListenJsx } from './listen-jsx.js';
export { ListenJsxRoot, defineCustomElement as defineCustomElementListenJsxRoot } from './listen-jsx-root.js';
export { ListenReattach, defineCustomElement as defineCustomElementListenReattach } from './listen-reattach.js';
export { ListenWindow, defineCustomElement as defineCustomElementListenWindow } from './listen-window.js';
export { NoDelegatesFocus, defineCustomElement as defineCustomElementNoDelegatesFocus } from './no-delegates-focus.js';
export { NodeGlobals, defineCustomElement as defineCustomElementNodeGlobals } from './node-globals.js';
export { NodeResolution, defineCustomElement as defineCustomElementNodeResolution } from './node-resolution.js';
export { ParentReflectNanAttribute, defineCustomElement as defineCustomElementParentReflectNanAttribute } from './parent-reflect-nan-attribute.js';
export { ParentWithReflectChild, defineCustomElement as defineCustomElementParentWithReflectChild } from './parent-with-reflect-child.js';
export { ReflectNanAttribute, defineCustomElement as defineCustomElementReflectNanAttribute } from './reflect-nan-attribute.js';
export { ReflectNanAttributeHyphen, defineCustomElement as defineCustomElementReflectNanAttributeHyphen } from './reflect-nan-attribute-hyphen.js';
export { ReflectToAttr, defineCustomElement as defineCustomElementReflectToAttr } from './reflect-to-attr.js';
export { ReparentStyleNoVars, defineCustomElement as defineCustomElementReparentStyleNoVars } from './reparent-style-no-vars.js';
export { ReparentStyleWithVars, defineCustomElement as defineCustomElementReparentStyleWithVars } from './reparent-style-with-vars.js';
export { SassCmp, defineCustomElement as defineCustomElementSassCmp } from './sass-cmp.js';
export { ScopedBasic, defineCustomElement as defineCustomElementScopedBasic } from './scoped-basic.js';
export { ScopedBasicRoot, defineCustomElement as defineCustomElementScopedBasicRoot } from './scoped-basic-root.js';
export { ShadowDomArray, defineCustomElement as defineCustomElementShadowDomArray } from './shadow-dom-array.js';
export { ShadowDomArrayRoot, defineCustomElement as defineCustomElementShadowDomArrayRoot } from './shadow-dom-array-root.js';
export { ShadowDomBasic, defineCustomElement as defineCustomElementShadowDomBasic } from './shadow-dom-basic.js';
export { ShadowDomBasicRoot, defineCustomElement as defineCustomElementShadowDomBasicRoot } from './shadow-dom-basic-root.js';
export { ShadowDomMode, defineCustomElement as defineCustomElementShadowDomMode } from './shadow-dom-mode.js';
export { ShadowDomModeRoot, defineCustomElement as defineCustomElementShadowDomModeRoot } from './shadow-dom-mode-root.js';
export { ShadowDomSlotBasic, defineCustomElement as defineCustomElementShadowDomSlotBasic } from './shadow-dom-slot-basic.js';
export { ShadowDomSlotNested, defineCustomElement as defineCustomElementShadowDomSlotNested } from './shadow-dom-slot-nested.js';
export { ShadowDomSlotNestedRoot, defineCustomElement as defineCustomElementShadowDomSlotNestedRoot } from './shadow-dom-slot-nested-root.js';
export { SiblingRoot, defineCustomElement as defineCustomElementSiblingRoot } from './sibling-root.js';
export { SlotArrayBasic, defineCustomElement as defineCustomElementSlotArrayBasic } from './slot-array-basic.js';
export { SlotArrayComplex, defineCustomElement as defineCustomElementSlotArrayComplex } from './slot-array-complex.js';
export { SlotArrayComplexRoot, defineCustomElement as defineCustomElementSlotArrayComplexRoot } from './slot-array-complex-root.js';
export { SlotArrayTop, defineCustomElement as defineCustomElementSlotArrayTop } from './slot-array-top.js';
export { SlotBasic, defineCustomElement as defineCustomElementSlotBasic } from './slot-basic.js';
export { SlotBasicOrder, defineCustomElement as defineCustomElementSlotBasicOrder } from './slot-basic-order.js';
export { SlotBasicOrderRoot, defineCustomElement as defineCustomElementSlotBasicOrderRoot } from './slot-basic-order-root.js';
export { SlotBasicRoot, defineCustomElement as defineCustomElementSlotBasicRoot } from './slot-basic-root.js';
export { SlotChildrenRoot, defineCustomElement as defineCustomElementSlotChildrenRoot } from './slot-children-root.js';
export { SlotDynamicScopedList, defineCustomElement as defineCustomElementSlotDynamicScopedList } from './slot-dynamic-scoped-list.js';
export { SlotDynamicShadowList, defineCustomElement as defineCustomElementSlotDynamicShadowList } from './slot-dynamic-shadow-list.js';
export { SlotDynamicWrapper, defineCustomElement as defineCustomElementSlotDynamicWrapper } from './slot-dynamic-wrapper.js';
export { SlotDynamicWrapperRoot, defineCustomElement as defineCustomElementSlotDynamicWrapperRoot } from './slot-dynamic-wrapper-root.js';
export { SlotFallback, defineCustomElement as defineCustomElementSlotFallback } from './slot-fallback.js';
export { SlotFallbackRoot, defineCustomElement as defineCustomElementSlotFallbackRoot } from './slot-fallback-root.js';
export { SlotHtml, defineCustomElement as defineCustomElementSlotHtml } from './slot-html.js';
export { SlotLightDomContent, defineCustomElement as defineCustomElementSlotLightDomContent } from './slot-light-dom-content.js';
export { SlotLightDomRoot, defineCustomElement as defineCustomElementSlotLightDomRoot } from './slot-light-dom-root.js';
export { SlotLightList, defineCustomElement as defineCustomElementSlotLightList } from './slot-light-list.js';
export { SlotLightScopedList, defineCustomElement as defineCustomElementSlotLightScopedList } from './slot-light-scoped-list.js';
export { SlotListLightRoot, defineCustomElement as defineCustomElementSlotListLightRoot } from './slot-list-light-root.js';
export { SlotListLightScopedRoot, defineCustomElement as defineCustomElementSlotListLightScopedRoot } from './slot-list-light-scoped-root.js';
export { SlotMapOrder, defineCustomElement as defineCustomElementSlotMapOrder } from './slot-map-order.js';
export { SlotMapOrderRoot, defineCustomElement as defineCustomElementSlotMapOrderRoot } from './slot-map-order-root.js';
export { SlotNestedOrderChild, defineCustomElement as defineCustomElementSlotNestedOrderChild } from './slot-nested-order-child.js';
export { SlotNestedOrderParent, defineCustomElement as defineCustomElementSlotNestedOrderParent } from './slot-nested-order-parent.js';
export { SlotNgIf, defineCustomElement as defineCustomElementSlotNgIf } from './slot-ng-if.js';
export { SlotNoDefault, defineCustomElement as defineCustomElementSlotNoDefault } from './slot-no-default.js';
export { SlotReorder, defineCustomElement as defineCustomElementSlotReorder } from './slot-reorder.js';
export { SlotReorderRoot, defineCustomElement as defineCustomElementSlotReorderRoot } from './slot-reorder-root.js';
export { SlotReplaceWrapper, defineCustomElement as defineCustomElementSlotReplaceWrapper } from './slot-replace-wrapper.js';
export { SlotReplaceWrapperRoot, defineCustomElement as defineCustomElementSlotReplaceWrapperRoot } from './slot-replace-wrapper-root.js';
export { SlottedCss, defineCustomElement as defineCustomElementSlottedCss } from './slotted-css.js';
export { StaticStyles, defineCustomElement as defineCustomElementStaticStyles } from './static-styles.js';
export { StencilSibling, defineCustomElement as defineCustomElementStencilSibling } from './stencil-sibling.js';
export { SvgAttr, defineCustomElement as defineCustomElementSvgAttr } from './svg-attr.js';
export { SvgClass, defineCustomElement as defineCustomElementSvgClass } from './svg-class.js';
export { Tag3dComponent, defineCustomElement as defineCustomElementTag3dComponent } from './tag-3d-component.js';
export { Tag88, defineCustomElement as defineCustomElementTag88 } from './tag-88.js';

Context.someSetting = true;

const globalScript = () => {
  Context['myService'] = 12;
  setMode((elm) => {
    return elm.colormode || elm.getAttribute('colormode') || window.KarmaMode;
  });
};

const globalScripts = () => {
  globalScript();
};

globalScripts();
