/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface EdgeSimpleRender {}
}

declare namespace LocalJSX {
  interface EdgeSimpleRender extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'EdgeSimpleRender': Components.EdgeSimpleRender;
  }

  interface IntrinsicElements {
    'EdgeSimpleRender': LocalJSX.EdgeSimpleRender;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLEdgeSimpleRenderElement extends Components.EdgeSimpleRender, HTMLStencilElement {}
  var HTMLEdgeSimpleRenderElement: {
    prototype: HTMLEdgeSimpleRenderElement;
    new (): HTMLEdgeSimpleRenderElement;
  };
  interface HTMLElementTagNameMap {
    'edge-simple-render': HTMLEdgeSimpleRenderElement
  }

  interface ElementTagNameMap {
    'edge-simple-render': HTMLEdgeSimpleRenderElement;
  }
}

