name: 'Test End-to-End'
description: 'run end-to-end tests'
runs:
  using: 'composite'
  steps:
    # since this job runs on its own virtual machine, we need to get the dependencies (which may be cached for us)
    - name: Get Core Dependencies
      uses: ./.github/workflows/actions/get-core-dependencies

    - uses: ./.github/workflows/actions/download-archive
      with:
        name: stencil-core
        path: .
        filename: stencil-core-build.zip

    - name: End-to-End Tests
      run: npm run test.end-to-end -- --ci
      shell: bash
