/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface AppRoot {}
  interface ScopedMode {}
  interface ShadowMode {}
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface ScopedMode extends JSXBase.HTMLAttributes {}
  interface ShadowMode extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'AppRoot': Components.AppRoot;
    'ScopedMode': Components.ScopedMode;
    'ShadowMode': Components.ShadowMode;
  }

  interface IntrinsicElements {
    'AppRoot': LocalJSX.AppRoot;
    'ScopedMode': LocalJSX.ScopedMode;
    'ShadowMode': LocalJSX.ShadowMode;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLScopedModeElement extends Components.ScopedMode, HTMLStencilElement {}
  var HTMLScopedModeElement: {
    prototype: HTMLScopedModeElement;
    new (): HTMLScopedModeElement;
  };

  interface HTMLShadowModeElement extends Components.ShadowMode, HTMLStencilElement {}
  var HTMLShadowModeElement: {
    prototype: HTMLShadowModeElement;
    new (): HTMLShadowModeElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'scoped-mode': HTMLScopedModeElement
    'shadow-mode': HTMLShadowModeElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'scoped-mode': HTMLScopedModeElement;
    'shadow-mode': HTMLShadowModeElement;
  }
}

