/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { JSXElements } from '@stencil/core';




export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends JSXElements.HTMLAttributes {}

  interface ScopedMode {}
  interface ScopedModeAttributes extends JSXElements.HTMLAttributes {}

  interface ShadowMode {}
  interface ShadowModeAttributes extends JSXElements.HTMLAttributes {}
}

interface HTMLStencilElement extends HTMLElement {
  componentOnReady(): Promise<this>;
  forceUpdate(): void;
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'ScopedMode': Components.ScopedMode;
    'ShadowMode': Components.ShadowMode;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'scoped-mode': Components.ScopedModeAttributes;
    'shadow-mode': Components.ShadowModeAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLScopedModeElement extends Components.ScopedMode, HTMLStencilElement {}
  var HTMLScopedModeElement: {
    prototype: HTMLScopedModeElement;
    new (): HTMLScopedModeElement;
  };

  interface HTMLShadowModeElement extends Components.ShadowMode, HTMLStencilElement {}
  var HTMLShadowModeElement: {
    prototype: HTMLShadowModeElement;
    new (): HTMLShadowModeElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'scoped-mode': HTMLScopedModeElement
    'shadow-mode': HTMLShadowModeElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'scoped-mode': HTMLScopedModeElement;
    'shadow-mode': HTMLShadowModeElement;
  }

}
