/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TsTargetProps {
        "basicProp": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "basic-prop"?: string;
        "decoratedGetterSetterProp": number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "decorated-getter-setter-prop"?: number;
        "decoratedProp": number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "decorated-prop"?: number;
        "dynamicLifecycle": string[];
    }
}
declare global {
    interface HTMLTsTargetPropsElement extends Components.TsTargetProps, HTMLStencilElement {
    }
    var HTMLTsTargetPropsElement: {
        prototype: HTMLTsTargetPropsElement;
        new (): HTMLTsTargetPropsElement;
    };
    interface HTMLElementTagNameMap {
        "ts-target-props": HTMLTsTargetPropsElement;
    }
}
declare namespace LocalJSX {
    interface TsTargetProps {
        "basicProp"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "basic-prop"?: string;
        "decoratedGetterSetterProp"?: number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "decorated-getter-setter-prop"?: number;
        "decoratedProp"?: number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "decorated-prop"?: number;
        "dynamicLifecycle"?: string[];
    }
    interface IntrinsicElements {
        "ts-target-props": TsTargetProps;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ts-target-props": LocalJSX.TsTargetProps & JSXBase.HTMLAttributes<HTMLTsTargetPropsElement>;
        }
    }
}
