/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { JSXElements } from '@stencil/core';




export namespace Components {

  interface HelloVdom {}
  interface HelloVdomAttributes extends JSXElements.HTMLAttributes {}
}

interface HTMLStencilElement extends HTMLElement {
  componentOnReady(): Promise<this>;
  forceUpdate(): void;
}

declare global {
  interface StencilElementInterfaces {
    'HelloVdom': Components.HelloVdom;
  }

  interface StencilIntrinsicElements {
    'hello-vdom': Components.HelloVdomAttributes;
  }


  interface HTMLHelloVdomElement extends Components.HelloVdom, HTMLStencilElement {}
  var HTMLHelloVdomElement: {
    prototype: HTMLHelloVdomElement;
    new (): HTMLHelloVdomElement;
  };

  interface HTMLElementTagNameMap {
    'hello-vdom': HTMLHelloVdomElement
  }

  interface ElementTagNameMap {
    'hello-vdom': HTMLHelloVdomElement;
  }

}
