import color from 'ansi-colors';
import inquirer from 'inquirer';

import { BuildOptions } from './utils/options';
import { getNewVersion, isValidVersionInput, prettyVersionDiff, SEMVER_INCREMENTS } from './utils/release-utils';

/**
 * A type describing the answers to prompts for preparing a release
 */
export type PrepareReleasePromptAnswers = {
  /**
   * If `true`, run release preparation steps
   */
  confirm: boolean;
  /**
   * A semver compliant version, generated by the prompting question
   */
  version?: string;
  /**
   * A user defined version. This version takes precedence over {@link PrepareReleasePromptAnswers#version}.
   */
  specifiedVersion?: string;
};

/**
 * A type describing the normalized responses of {@link PrepareReleasePromptAnswers}
 */
export type NormalizedPrepareResponses = {
  /**
   * If `true`, run release preparation steps
   */
  confirm: boolean;
  /**
   * The semver string to publish use Stencil under
   */
  versionToUse: string;
};

/**
 * Prompts a developer to answer questions regarding how a release of Stencil should be performed
 * @param opts build options containing the metadata needed to release a new version of Stencil
 */
export async function promptPrepareRelease(opts: BuildOptions): Promise<NormalizedPrepareResponses> {
  const pkg = opts.packageJson;
  const oldVersion = opts.packageJson.version;

  const NON_SERVER_INCREMENTS: ReadonlyArray<{ name: string; value: string }> = [
    {
      name: 'Dry Run',
      value: getNewVersion(oldVersion, 'patch') + '-dryrun',
    },
    {
      name: 'Other (specify)',
      value: null,
    },
  ];

  const prompts: inquirer.QuestionCollection<PrepareReleasePromptAnswers> = [
    {
      type: 'list',
      name: 'version',
      message: 'Select semver increment or specify new version',
      pageSize: SEMVER_INCREMENTS.length + NON_SERVER_INCREMENTS.length,
      choices: SEMVER_INCREMENTS.map((inc) => ({
        name: `${inc}   ${prettyVersionDiff(oldVersion, inc)}`,
        value: inc,
      })).concat([new inquirer.Separator() as any, ...NON_SERVER_INCREMENTS]),
      filter: (input: string) => (isValidVersionInput(input) ? getNewVersion(oldVersion, input) : input),
    },
    {
      type: 'input',
      // this name is intentionally different from 'version' above to make the `when` check below work properly
      // (this prompt should only run if `version` was not already input)
      name: 'specifiedVersion',
      message: 'Specify Version',
      when: (answers: any) => !answers.version,
      filter: (input: string) => (isValidVersionInput(input) ? getNewVersion(pkg.version, input) : input),
      validate: (input: string) => {
        if (!isValidVersionInput(input)) {
          return 'Please specify a valid semver, for example, `1.2.3`, or `3.0.0-alpha.0`. See http://semver.org';
        }
        return true;
      },
    },
    {
      type: 'confirm',
      name: 'confirm',
      message: (answers: any) => {
        const version = determineAnsweredVersionToUse(answers);
        return `Prepare release ${opts.vermoji}  ${color.yellow(version)} from ${oldVersion}. Continue?`;
      },
    },
  ];

  try {
    const answers = await inquirer.prompt<PrepareReleasePromptAnswers>(prompts);
    return {
      confirm: answers.confirm,
      versionToUse: determineAnsweredVersionToUse(answers),
    };
  } catch (err: any) {
    console.log('\n', color.red(err), '\n');
    process.exit(0);
  }
}

/**
 * Helper function to determine which version string to use.
 *
 * Due to a bug in Inquirer, the version to publish Stencil under needs to be specified under two different fields when
 * the release preparation scripts diverge in questioning. This function ensures the logic for determining which of
 * those two answers is to be used.
 *
 * @param answers user provided answers to pick from
 * @returns the version string to use. defaults to 'UNKNOWN' if the version cannot be determined.
 */
export function determineAnsweredVersionToUse(answers: PrepareReleasePromptAnswers): string {
  return answers.version ? answers.version : answers.specifiedVersion ? answers.specifiedVersion : 'UNKNOWN';
}

/**
 * A type describing the answers to prompts for performing a release
 */
export type ReleasePromptAnswers = {
  /**
   * If `true`, run release steps
   */
  confirm: boolean;
  /**
   * A one-time password, provided by a developer's authenticator application
   */
  otp: string;
  /**
   * A user specified tag to push to the npm registry. If provided, this overrider {@link ReleasePromptAnswers#tag}
   */
  specifiedTag?: string;
  /**
   * The tag to push to the npm registry. This is _not_ the tag pushed to GitHub
   */
  tag?: string;
};
