/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface AppRoot {}
  interface TodoInput {}
  interface TodoItem {
    'checked': boolean;
    'index': number;
    'text': string;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface TodoInput extends JSXBase.HTMLAttributes {
    'onInputSubmit'?: (event: CustomEvent<any>) => void;
  }
  interface TodoItem extends JSXBase.HTMLAttributes {
    'checked'?: boolean;
    'index'?: number;
    'onItemCheck'?: (event: CustomEvent<any>) => void;
    'onItemRemove'?: (event: CustomEvent<any>) => void;
    'text'?: string;
  }

  interface ElementInterfaces {
    'AppRoot': Components.AppRoot;
    'TodoInput': Components.TodoInput;
    'TodoItem': Components.TodoItem;
  }

  interface IntrinsicElements {
    'AppRoot': LocalJSX.AppRoot;
    'TodoInput': LocalJSX.TodoInput;
    'TodoItem': LocalJSX.TodoItem;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLTodoInputElement extends Components.TodoInput, HTMLStencilElement {}
  var HTMLTodoInputElement: {
    prototype: HTMLTodoInputElement;
    new (): HTMLTodoInputElement;
  };

  interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {}
  var HTMLTodoItemElement: {
    prototype: HTMLTodoItemElement;
    new (): HTMLTodoItemElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'todo-input': HTMLTodoInputElement
    'todo-item': HTMLTodoItemElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'todo-input': HTMLTodoInputElement;
    'todo-item': HTMLTodoItemElement;
  }
}

