(window.Ionic=window.Ionic||{}).components={"ion-badge":[{"ios":"0","md":"1","wp":"2"}]};
/*! (C) Ionic, https://ionicframework.com/ - Mit License */
(function(u,C){"use-strict";function n(a){return void 0!==a&&null!==a}function G(a){return"string"===typeof a||"number"===typeof a}function M(a){return a.replace(/-([a-z])/g,function(a){return a[1].toUpperCase()})}function T(a){return a.replace(/([A-Z])/g,function(a){return"-"+a[0].toLowerCase()})}function N(a,c){if("boolean"===a)return"string"===typeof c?"false"!==c:!!c;if("number"===a){if("number"===typeof c)return c;try{return parseFloat(c)}catch(d){}return NaN}return c}function U(){}function H(a,c,d,f,e){return{f:a,
b:c,i:d,c:f,a:e,j:void 0===c?void 0:c.key}}function O(a,c){var d,f,e=c.a;a=a.b.O;var b=c.b.O;if((a||b)&&a!==b){a=a||{};b=b||{};for(d in b)c=b[d],f=a[d],f!==c&&("boolean"===typeof c?c?e.setAttribute(d,""):e.removeAttribute(d):120!==d.charCodeAt(0)?e.setAttribute(d,c):58===d.charCodeAt(3)?e.setAttributeNS("http://www.w3.org/XML/1998/namespace",d,c):58===d.charCodeAt(5)?e.setAttributeNS("http://www.w3.org/1999/xlink",d,c):e.setAttribute(d,c));for(d in a)d in b||e.removeAttribute(d)}}function P(a,c){var d,
f=c.a;a=a.b.F;var e=c.b.F;if((a||e)&&a!==e){a=a||{};e=e||{};for(d in a)e[d]||f.classList.remove(d);for(d in e)if(c=e[d],c!==a[d])f.classList[c?"add":"remove"](d)}}function Q(a,c,d){a.W="http://www.w3.org/2000/svg";if("foreignObject"!==d&&void 0!==c)for(a=0;a<c.length;++a)d=c[a].b,void 0!==d&&Q(d,c[a].i,c[a].f)}function I(a,c,d){var f={},e,b,l=void 0;a.nodeType&&(l=a);void 0!==d?(f=c,J(d)?e=d:G(d)?b=d:d&&d.f&&(e=[d])):void 0!==c&&(J(c)?e=c:G(c)?b=c:c&&c.f?e=[c]:f=c);if(J(e))for(c=0;c<e.length;++c)G(e[c])&&
(e[c]=H(void 0,void 0,void 0,e[c]));"s"!==a[0]||"v"!==a[1]||"g"!==a[2]||3!==a.length&&"."!==a[3]&&"#"!==a[3]||Q(f,e,a);return H(a,f,e,b,l)}function F(a,c){return a.j===c.j&&a.f===c.f}function R(a,c,d){var f={};f[""+a]=!0;c&&(f[a+"-"+c]=!0,d&&(f[a+"-"+d]=f[a+"-"+c+"-"+d]=!0));return{F:f}}function V(a,c,d,f,e,b,l,k){var g=b.m,t={};Object.keys(k).forEach(function(h){function m(){return t[h]}t[h]=W(c,d,e,k,h);Object.defineProperty(e,h,{get:m,set:function(k){t[h]!==k&&(t[h]=k,S(a,c,d,f,e,b,l))}});Object.defineProperty(g,
h,{get:m,set:function(){console.error(h+": passed in property values cannot be changed")}})})}function W(a,c,d,f,e){var b=d[e];if(void 0!==b)return b;b=a.A(d,M(e));if(null!==b&&""!==b)return N(f[e].type,b);b=c.get(e);if(null!==b)return b}function S(a,c,d,f,e,b,l){b.G||(b.G=!0,c.nextTick(function(){var k=c.S(l),g=b.m;g||(g=b.m=new k.R,V(a,c,d,f,e,b,l,k.props));b.o||(b.o=c.I(e,k.modes[g.mode],l+"."+g.mode));var t=b.o,k=k.T,h=g.Y&&g.Y(I,a);h||(h=I(t,I("div",R(k,g.mode,g.color),I("slot"))));delete h.f;
b.u=f(b.u?b.u:e,h);b.G=!1}))}function X(a,c,d,f,e,b,l){c.nextTick(function(){var k=l.tag,g=Y(c,d,e);c.V(l,l.modes[g],function(){S(a,c,d,f,e,b,k)})})}function Y(a,c,d){var f=d.mode;if(n(f))return f;f=a.A(d,"mode");return n(f)?f:c.get("mode","md")}var J=Array.isArray,L=H("",{},[],void 0,void 0),K=u.Ionic=u.Ionic||{},Z=function(a){function c(){e=!0;a.requestAnimationFrame(function(a){var b,k,g;try{for(b=performance.now();k=d.shift();)k(a);for(;(k=f.shift())&&!(k(a),8<performance.now()-b););}catch(t){g=
t}e=!1;(d.length||f.length)&&c();if(g)throw g;})}var d=[],f=[],e=void 0;return{read:function(a){d.push(a);e||c()},write:function(a){f.push(a);e||c()}}}(u),aa=function(a){function c(){f=!1;for(var a=d.slice(0),b=d.length=0;b<a.length;b++)a[b]()}var d=[],f=!1,e=void 0,b=/iphone|ipad|ipod|ios/.test(a.navigator.userAgent.toLowerCase());if("undefined"!==typeof Promise&&-1!==Promise.toString().indexOf("[native code]"))var l=Promise.resolve(),k=function(a){console.error(a)},e=function(){l.then(c).catch(k);
b&&setTimeout(U)};else e=function(){setTimeout(c,0)};return{nextTick:function(a){d.push(a);f||(f=!0,e())}}}(u);C=function(a,c,d,f,e,b){function l(a){function b(){clearTimeout(q);d.onerror=d.onload=null;d.parentNode.removeChild(d);var b=h.indexOf(a);-1<b&&h.splice(b,1)}h.push(a);var d=k("script");d.charset="utf-8";d.async=!0;d.src=a;var q=setTimeout(b,12E4);d.onerror=d.onload=b;c.head.appendChild(d)}function k(a){return c.createElement(a)}var g={},t={},h=[],m={},n=!(a.N&&a.N.ca);d.loadComponents=function(a,
b){var c=g[b[0]],d=c.modes[b[1]];d.H=b[2];var e={};(0,b[3])(e);c.R=e[Object.keys(e)[0]];d.U=!0;if(b=t[a]){c=0;for(d=b.length;c<d;c++)b[c]();delete t[a]}};return{X:function(a,b){var c=b[0];b=b[1]||{};a=g[a]={tag:a,modes:{},props:b};for(var d=Object.keys(c),e=0;e<d.length;e++)a.modes[d[e]]={P:c[d[e]]};d=a.tag.split("-");d.shift();a.T=d.join("-");b.color={};b.mode={};c=a.observedAttrs=a.observedAttrs||[];d=Object.keys(b);for(e=0;e<d.length;e++)c.push(T(d[e]));return a},S:function(a){return g[a]},V:function(a,
b,c){b&&b.U?c(a,b):(a=b.P,t[a]?t[a].push(c):t[a]=[c],c=f+"ionic."+a,d.devMode&&(c+=".dev"),c+=".js",-1===h.indexOf(c)&&l(c))},ga:function(a){return 1===a.nodeType},ha:function(a){return 3===a.nodeType},fa:function(a){return 8===a.nodeType},nextTick:b.nextTick.bind(b),aa:e.read.bind(e),ba:e.write.bind(e),K:k,L:function(a,b){return c.createElementNS(a,b)},w:function(a){return c.createTextNode(a)},J:function(a){return c.createComment(a)},g:function(a,b,c){a.insertBefore(b,c)},D:function(a,b){a.removeChild(b)},
v:function(a,b){a.appendChild(b)},C:function(a){return a.parentNode},B:function(a){return a.nextSibling},M:function(a){return(a.tagName||"").toLowerCase()},l:function(a,b){a.textContent=b},Z:function(a){return a.textContent},A:function(a,b){return a.getAttribute(b)},I:function(a,b,d){a=a.attachShadow({mode:"open"});if(n)b.s||(b.s=k("style"),b.s.innerHTML=b.H),a.appendChild(b.s.cloneNode(!0));else if(!m[d]){var e=k("style");e.dataset.cmpModeId=d;e.innerHTML=b.H.replace(/\:host\-context\((.*?)\)|:host\((.*?)\)|\:host/g,
"__h");c.head.appendChild(e);m[d]=!0}return a}}}(u,C,K,K.staticDir,Z,aa);(function(a,c,d,f){var e=new WeakMap,b={theme:R};Object.keys(f||{}).forEach(function(l){class k extends HTMLElement {}var g=c.X(l,f[l]);k.prototype.connectedCallback=function(){var k={};e.set(this,k);X(b,c,d,a,this,k,g)};k.prototype.attributeChangedCallback=function(a,b,c){b!==c&&(a=M(a),g.props[a]&&(this[a]=N(g.props[a].type,c)))};k.prototype.disconnectedCallback=function(){var a=e.get(this);a&&(a.m=a.u=a.o=null);e.delete(this)};
k.observedAttributes=g.observedAttrs;u.customElements.define(l,k)})})(function(a){function c(b){return function(){a.D(a.C(b),b)}}function d(b,c){var e=void 0,g=b.b;void 0!==g&&n(e=g.h)&&n(e=e.da)&&(e(b),g=b.b);var f=b.i,h=b.f;if("!"===h)void 0===b.c&&(b.c=""),b.a=a.J(b.c);else if(void 0!==h){var l=h.indexOf("#"),p=h.indexOf(".",l),q=0<l?l:h.length,r=0<p?p:h.length,l=-1!==l||-1!==p?h.slice(0,Math.min(q,r)):h,g=b.a=n(g)&&n(e=g.W)?a.L(e,l):a.K(l);q<r&&(g.id=h.slice(q+1,r));0<p&&(g.className=h.slice(r+
1).replace(/\./g," "));O(L,b);P(L,b);if(J(f))for(e=0;e<f.length;++e)h=f[e],null!=h&&a.v(g,d(h,c));else G(b.c)&&a.v(g,a.w(b.c));e=b.b.h;n(e)&&(e.create&&e.create(L,b),e.ea&&c.push(b))}else b.a=a.w(b.c);return b.a}function f(b,d,e,g){for(;e<=g;++e){var f=void 0,h,l=d[e];null!=l&&(n(l.f)?(h=c(l.a),n(f=l.b)&&n(f=f.h)&&n(f=f.remove)?f(l,h):h()):a.D(b,l.a))}}function e(b,c,k){var g=void 0,l=void 0;n(g=c.b)&&n(l=g.h)&&n(g=l.ja)&&g(b,c);var h=c.a=b.a,m=b.i,p=c.i;if(b!==c){void 0!==c.b&&(O(b,c),P(b,c),g=c.b.h,
n(g)&&n(g=g.update)&&g(b,c));if(void 0===c.c)if(n(m)&&n(p)){if(m!==p){for(var h=h.shadowRoot||h,q=0,r=0,z=m.length-1,v=m[0],y=m[z],w=p.length-1,x=p[0],A=p[w],B=void 0,u,D;q<=z&&r<=w;)if(null==v)v=m[++q];else if(null==y)y=m[--z];else if(null==x)x=p[++r];else if(null==A)A=p[--w];else if(F(v,x))e(v,x,k),v=m[++q],x=p[++r];else if(F(y,A))e(y,A,k),y=m[--z],A=p[--w];else if(F(v,A))e(v,A,k),a.g(h,v.a,a.B(y.a)),v=m[++q],A=p[--w];else{if(F(y,x))e(y,x,k),a.g(h,y.a,v.a),y=m[--z];else{if(void 0===B){var E;u=m;
D=z;for(var C={},B=q;B<=D;++B)E=u[B],null!=E&&(E=E.j,void 0!==E&&(C[E]=B));B=C}u=B[x.j];void 0===u?a.g(h,d(x,k),v.a):(D=m[u],D.f!==x.f?a.g(h,d(x,k),v.a):(e(D,x,k),m[u]=void 0,a.g(h,D.a,v.a)))}x=p[++r]}if(q>z)for(m=null==p[w+1]?null:p[w+1].a;r<=w;++r)q=p[r],null!=q&&a.g(h,d(q,k),m);else r>w&&f(h,m,q,z)}}else if(n(p))for(n(b.c)&&a.l(h,""),w=0,m=p.length-1;w<=m;++w)r=p[w],null!=r&&a.g(h,d(r,k),null);else n(m)?f(h,m,0,m.length-1):n(b.c)&&a.l(h,"");else b.c!==c.c&&a.l(h,c.c);n(l)&&n(g=l.ia)&&g(b,c)}}return function(b,
c){var k,g,l=[];void 0!==b.f||void 0!==b.a||(b=H(a.M(b)+(b.id?"#"+b.id:"")+(b.className?"."+b.className.split(" ").join("."):""),{},[],void 0,b));c.a||F(b,c)?e(b,c,l):(k=b.a,g=a.C(k),d(c,l),null!==g&&(a.g(g,c.a,a.B(k)),f(g,[b],0,0)));return c}}(C),C,function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};return{get:function(c){return"mode"===c?"md":a[c]?a[c]:1<arguments.length&&void 0!==arguments[1]?arguments[1]:null}}}(K.$||{}),K.components)})(window,document);
