name: 'Build Stencil Core'
description: 'builds the core compiler'
runs:
  using: composite
  steps:
    # since this job runs on its own virtual machine, we need to get the dependencies (which may be cached for us)
    - name: Get Core Dependencies
      uses: ./.github/workflows/actions/get-core-dependencies

    - name: Build
      run: npm run build -- --ci
      shell: bash

    - name: Validate Build
      run: npm run test.dist
      shell: bash

    - name: Validate Testing
      run: npm run test.testing
      shell: bash

    - name: Upload Build Artifacts
      uses: ./.github/workflows/actions/upload-archive
      with:
        name: stencil-core
        output: stencil-core-build.zip
        paths: build cli compiler dependencies.json dev-server internal mock-doc scripts screenshot sys testing

