var SiteMenu = (function () {
    function SiteMenu() {
    }
    SiteMenu.prototype.render = function () {
        return (h("div", null, h("ul", null, h("li", null, h("h4", null, "Introduction"), h("ul", null, h("li", null, h("stencil-route-link", { "url": "/docs/intro" }, "What is Stencil?")), h("li", null, h("stencil-route-link", { "url": "/docs/getting-started" }, "Getting Started")))), h("li", null, h("h4", null, "Basics"), h("ul", null, h("li", null, h("stencil-route-link", { "url": "/docs/my-first-component" }, "My First Component")), h("li", null, h("stencil-route-link", { "url": "/docs/templating" }, "Templating")), h("li", null, h("stencil-route-link", { "url": "/docs/decorators" }, "Decorators")), h("li", null, h("stencil-route-link", { "url": "/docs/events" }, "Events")), h("li", null, h("stencil-route-link", { "url": "/docs/component-lifecycle" }, "Component Life Cycle")))), h("li", null, h("h4", null, "Advanced"), h("ul", null, h("li", null, h("stencil-route-link", { "url": "/docs/stencil-config" }, "Stencil Configuration")), h("li", null, h("stencil-route-link", { "url": "/docs/prerendering" }, "Prerendering")), h("li", null, h("stencil-route-link", { "url": "/docs/server-side-rendering" }, "Server Side Rendering")), h("li", null, h("stencil-route-link", { "url": "/docs/service-workers" }, "Service Workers")), h("li", null, h("stencil-route-link", { "url": "/docs/distribution" }, "Distribution")))), h("li", null, h("h4", null, "Add-ons"), h("ul", null, h("li", null, h("stencil-route-link", { "url": "/docs/routing" }, "Router")))), h("li", null, h("h4", null, "Community"), h("ul", null, h("li", null, h("a", { "href": "https://join.slack.com/t/stencil-worldwide/shared_invite/enQtMjQ2MzkyMTY0MTk0LTQ4ODgzYjFjNjdkNDY3YWVhMmNlMTljMWQxNTM3Yjg0ZTIyZTM1MmU2YWE5YzNjNzE1MmQ3ZTk2NjQ1YzM5ZDM", "title": "Stencil slack channel" }, "Stencil Slack")), h("li", null, h("a", { "href": "https://twitter.com/stenciljs" }, "Stencil on Twitter")))))));
    };
    return SiteMenu;
}());
export { SiteMenu };
