/*! (C) Ionic, https://ionicframework.com/ - Mit License */
(function(C,G){"use-strict";function H(a,b,d,f,e){return{f:a,b:b,i:d,c:f,a:e,j:void 0===b?void 0:b.key}}function n(a){return void 0!==a&&null!==a}function I(a){return"string"===typeof a||"number"===typeof a}function M(a){return a.replace(/-([a-z])/g,function(a){return a[1].toUpperCase()})}function T(a){return a.replace(/([A-Z])/g,function(a){return"-"+a[0].toLowerCase()})}function N(a,b){if("boolean"===a)return"string"===typeof b?"false"!==b:!!b;if("number"===a){if("number"===typeof b)return b;try{return parseFloat(b)}catch(d){}return NaN}return b}
function O(a,b){var d,f,e=b.a;a=a.b.O;var c=b.b.O;if((a||c)&&a!==c){a=a||{};c=c||{};for(d in c)b=c[d],f=a[d],f!==b&&("boolean"===typeof b?b?e.setAttribute(d,""):e.removeAttribute(d):120!==d.charCodeAt(0)?e.setAttribute(d,b):58===d.charCodeAt(3)?e.setAttributeNS("http://www.w3.org/XML/1998/namespace",d,b):58===d.charCodeAt(5)?e.setAttributeNS("http://www.w3.org/1999/xlink",d,b):e.setAttribute(d,b));for(d in a)d in c||e.removeAttribute(d)}}function P(a,b){var d,f=b.a;a=a.b.F;var e=b.b.F;if((a||e)&&
a!==e){a=a||{};e=e||{};for(d in a)e[d]||f.classList.remove(d);for(d in e)if(b=e[d],b!==a[d])f.classList[b?"add":"remove"](d)}}function Q(a,b,d){a.W="http://www.w3.org/2000/svg";if("foreignObject"!==d&&void 0!==b)for(a=0;a<b.length;++a)d=b[a].b,void 0!==d&&Q(d,b[a].i,b[a].f)}function J(a,b,d){var f={},e,c,k=void 0;a.nodeType&&(k=a);void 0!==d?(f=b,K(d)?e=d:I(d)?c=d:d&&d.f&&(e=[d])):void 0!==b&&(K(b)?e=b:I(b)?c=b:b&&b.f?e=[b]:f=b);if(K(e))for(b=0;b<e.length;++b)I(e[b])&&(e[b]=H(void 0,void 0,void 0,
e[b]));"s"!==a[0]||"v"!==a[1]||"g"!==a[2]||3!==a.length&&"."!==a[3]&&"#"!==a[3]||Q(f,e,a);return H(a,f,e,c,k)}function F(a,b){return a.j===b.j&&a.f===b.f}function R(a,b,d){var f={};f[""+a]=!0;b&&(f[a+"-"+b]=!0,d&&(f[a+"-"+d]=f[a+"-"+b+"-"+d]=!0));return{F:f}}function U(a,b,d,f,e,c,k,h){var l=c.m,x={};Object.keys(h).forEach(function(g){function m(){return x[g]}x[g]=V(b,d,e,h,g);Object.defineProperty(e,g,{get:m,set:function(h){x[g]!==h&&(x[g]=h,S(a,b,d,f,e,c,k))}});Object.defineProperty(l,g,{get:m,
set:function(){console.error(g+": passed in property values cannot be changed")}})})}function V(a,b,d,f,e){var c=d[e];if(void 0!==c)return c;c=a.A(d,M(e));if(null!==c&&""!==c)return N(f[e].type,c);c=b.get(e);if(null!==c)return c}function W(a,b){var d=b[0];b=b[1]||{};a={tag:a,modes:{},props:b};for(var f=Object.keys(d),e=0;e<f.length;e++)a.modes[f[e]]={P:d[f[e]]};f=a.tag.split("-");f.shift();a.T=f.join("-");b.color={};b.mode={};d=a.observedAttrs=a.observedAttrs||[];f=Object.keys(b);for(e=0;e<f.length;e++)d.push(T(f[e]));
return a}function S(a,b,d,f,e,c,k){c.G||(c.G=!0,b.nextTick(function(){var h=b.S(k),l=c.m;l||(l=c.m=new h.R,U(a,b,d,f,e,c,k,h.props));c.o||(c.o=b.I(e,h.modes[l.mode],k+"."+l.mode));var x=c.o,h=h.T,g=l.Y&&l.Y(J,a);g||(g=J(x,J("div",R(h,l.mode,l.color),J("slot"))));delete g.f;c.u=f(c.u?c.u:e,g);c.G=!1}))}function X(a,b,d,f,e,c,k){b.nextTick(function(){var h=k.tag,l=Y(b,d,e);b.V(k,k.modes[l],function(){S(a,b,d,f,e,c,h)})})}function Y(a,b,d){var f=d.mode;if(n(f))return f;f=a.A(d,"mode");return n(f)?f:
b.get("mode","md")}var K=Array.isArray,L=H("",{},[],void 0,void 0),t=C.Ionic=C.Ionic||{};G=function(a,b,d,f,e,c){function k(a){function c(){clearTimeout(e);d.onerror=d.onload=null;d.parentNode.removeChild(d);var c=g.indexOf(a);-1<c&&g.splice(c,1)}g.push(a);var d=h("script");d.charset="utf-8";d.async=!0;d.src=a;var e=setTimeout(c,12E4);d.onerror=d.onload=c;b.head.appendChild(d)}function h(a){return b.createElement(a)}var l={},x={},g=[],m={},n=!(a.N&&a.N.ba);d.loadComponents=function(a){for(var c=arguments,
b=1;b<c.length;b++){var d=c[b],e=l[d[0]],q=e.modes[d[1]];q.H=d[2];var h={};(0,d[3])(h);e.R=h[Object.keys(h)[0]];q.U=!0}if(c=x[a]){b=0;for(d=c.length;b<d;b++)c[b]();delete x[a]}};return{X:function(a){l[a.tag]=a},S:function(a){return l[a]},V:function(a,c,b){c&&c.U?b(a,c):(a=c.P,x[a]?x[a].push(b):x[a]=[b],b=f+"ionic."+a,d.devMode&&(b+=".dev"),b+=".js",-1===g.indexOf(b)&&k(b))},fa:function(a){return 1===a.nodeType},ga:function(a){return 3===a.nodeType},ea:function(a){return 8===a.nodeType},nextTick:c.nextTick.bind(c),
$:e.read.bind(e),aa:e.write.bind(e),K:h,L:function(a,c){return b.createElementNS(a,c)},w:function(a){return b.createTextNode(a)},J:function(a){return b.createComment(a)},g:function(a,c,b){a.insertBefore(c,b)},D:function(a,c){a.removeChild(c)},v:function(a,c){a.appendChild(c)},C:function(a){return a.parentNode},B:function(a){return a.nextSibling},M:function(a){return(a.tagName||"").toLowerCase()},l:function(a,c){a.textContent=c},Z:function(a){return a.textContent},A:function(a,c){return a.getAttribute(c)},
I:function(a,c,d){a=a.attachShadow({mode:"open"});if(n)c.s||(c.s=h("style"),c.s.innerHTML=c.H),a.appendChild(c.s.cloneNode(!0));else if(!m[d]){var e=h("style");e.dataset.cmpModeId=d;e.innerHTML=c.H.replace(/\:host\-context\((.*?)\)|:host\((.*?)\)|\:host/g,"__h");b.head.appendChild(e);m[d]=!0}return a}}}(C,G,t,t.staticDir,t.domCtrl,t.nextTickCtrl);(function(a,b,d,f){var e=new WeakMap,c={theme:R};Object.keys(f||{}).forEach(function(k){class h extends HTMLElement {}var l=W(k,f[k]);b.X(l);h.prototype.connectedCallback=
function(){var h={};e.set(this,h);X(c,b,d,a,this,h,l)};h.prototype.attributeChangedCallback=function(a,c,b){c!==b&&(a=M(a),l.props[a]&&(this[a]=N(l.props[a].type,b)))};h.prototype.disconnectedCallback=function(){var a=e.get(this);a&&(a.m=a.u=a.o=null);e.delete(this)};h.observedAttributes=l.observedAttrs;C.customElements.define(k,h)})})(function(a){function b(c){return function(){a.D(a.C(c),c)}}function d(c,b){var e=void 0,f=c.b;void 0!==f&&n(e=f.h)&&n(e=e.ca)&&(e(c),f=c.b);var k=c.i,g=c.f;if("!"===
g)void 0===c.c&&(c.c=""),c.a=a.J(c.c);else if(void 0!==g){var m=g.indexOf("#"),p=g.indexOf(".",m),q=0<m?m:g.length,r=0<p?p:g.length,m=-1!==m||-1!==p?g.slice(0,Math.min(q,r)):g,f=c.a=n(f)&&n(e=f.W)?a.L(e,m):a.K(m);q<r&&(f.id=g.slice(q+1,r));0<p&&(f.className=g.slice(r+1).replace(/\./g," "));O(L,c);P(L,c);if(K(k))for(e=0;e<k.length;++e)g=k[e],null!=g&&a.v(f,d(g,b));else I(c.c)&&a.v(f,a.w(c.c));e=c.b.h;n(e)&&(e.create&&e.create(L,c),e.da&&b.push(c))}else c.a=a.w(c.c);return c.a}function f(c,d,e,f){for(;e<=
f;++e){var h=void 0,g,k=d[e];null!=k&&(n(k.f)?(g=b(k.a),n(h=k.b)&&n(h=h.h)&&n(h=h.remove)?h(k,g):g()):a.D(c,k.a))}}function e(c,b,h){var l=void 0,k=void 0;n(l=b.b)&&n(k=l.h)&&n(l=k.ia)&&l(c,b);var g=b.a=c.a,m=c.i,p=b.i;if(c!==b){void 0!==b.b&&(O(c,b),P(c,b),l=b.b.h,n(l)&&n(l=l.update)&&l(c,b));if(void 0===b.c)if(n(m)&&n(p)){if(m!==p){for(var g=g.shadowRoot||g,q=0,r=0,z=m.length-1,u=m[0],y=m[z],v=p.length-1,w=p[0],A=p[v],B=void 0,t,D;q<=z&&r<=v;)if(null==u)u=m[++q];else if(null==y)y=m[--z];else if(null==
w)w=p[++r];else if(null==A)A=p[--v];else if(F(u,w))e(u,w,h),u=m[++q],w=p[++r];else if(F(y,A))e(y,A,h),y=m[--z],A=p[--v];else if(F(u,A))e(u,A,h),a.g(g,u.a,a.B(y.a)),u=m[++q],A=p[--v];else{if(F(y,w))e(y,w,h),a.g(g,y.a,u.a),y=m[--z];else{if(void 0===B){var E;t=m;D=z;for(var C={},B=q;B<=D;++B)E=t[B],null!=E&&(E=E.j,void 0!==E&&(C[E]=B));B=C}t=B[w.j];void 0===t?a.g(g,d(w,h),u.a):(D=m[t],D.f!==w.f?a.g(g,d(w,h),u.a):(e(D,w,h),m[t]=void 0,a.g(g,D.a,u.a)))}w=p[++r]}if(q>z)for(m=null==p[v+1]?null:p[v+1].a;r<=
v;++r)q=p[r],null!=q&&a.g(g,d(q,h),m);else r>v&&f(g,m,q,z)}}else if(n(p))for(n(c.c)&&a.l(g,""),v=0,m=p.length-1;v<=m;++v)r=p[v],null!=r&&a.g(g,d(r,h),null);else n(m)?f(g,m,0,m.length-1):n(c.c)&&a.l(g,"");else c.c!==b.c&&a.l(g,b.c);n(k)&&n(l=k.ha)&&l(c,b)}}return function(b,k){var c,l,n=[];void 0!==b.f||void 0!==b.a||(b=H(a.M(b)+(b.id?"#"+b.id:"")+(b.className?"."+b.className.split(" ").join("."):""),{},[],void 0,b));k.a||F(b,k)?e(b,k,n):(c=b.a,l=a.C(c),d(k,n),null!==l&&(a.g(l,k.a,a.B(c)),f(l,[b],
0,0)));return k}}(G),G,t.configCtrl,t.components)})(window,document);
