name: BrowserStack

on:
  pull_request_target:
    branches:
      - master

permissions: read-all

env:
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}

jobs:
  browserstack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ format('refs/pull/{0}/merge', github.event.number) }}
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --ci

      - name: Start BrowserStack
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: Run karma tests
        run: npm run test.karma.prod

      - name: Stop BrowserStack
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
