name: BrowserStack Tests

on:
  pull_request_target:
    branches:
      - 'main'
      - 'v3.0.0-dev'
  push:
    branches:
      - 'main'
      - 'v3.0.0-dev'

jobs:
  browser-tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        with:
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/merge', github.event.number) || '' }}
          persist-credentials: false

      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3.1.1
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --ci

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Start BrowserStack
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: Run karma tests
        run: npm run test.karma.prod

      - name: Stop BrowserStack
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
