name: Rollup (legacy) CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_core:
    name: Build
    uses: ./.github/workflows/build-rollup.yml

  analysis_tests:
    name: Analysis Tests (Esbuild)
    needs: [build_core]
    uses: ./.github/workflows/test-analysis.yml
    with:
      build_name: stencil-core-rollup

  bundler_tests:
    name: Bundler Tests (Esbuild)
    needs: [build_core]
    uses: ./.github/workflows/test-bundlers.yml
    with:
      build_name: stencil-core-rollup

  component_starter_tests:
    name: Component Starter Smoke Test (Esbuild)
    needs: [build_core]
    uses: ./.github/workflows/test-component-starter.yml
    with:
      build_name: stencil-core-rollup

  e2e_tests:
    name: E2E Tests (Esbuild)
    needs: [build_core]
    uses: ./.github/workflows/test-e2e.yml
    with:
      build_name: stencil-core-rollup

  unit_tests:
    name: Unit Tests (Esbuild)
    needs: [build_core]
    uses: ./.github/workflows/test-unit.yml
    with:
      build_name: stencil-core-rollup
