name: Auto Request Review

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft && github.event.pull_request.user.type != 'Bot'  }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: ./.github/workflows/actions/auto-request-reviews
        with:
          orgReadToken: ${{ secrets.READORG_GITHUB_TOKEN }}
          writeToken: ${{ secrets.GITHUB_TOKEN }}
          org: 'ionic-team'
          team: 'stencil'
