name: Auto Request Review

on:
  pull_request:
    # TODO remove synchronize event
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  auto-request-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      - uses: ./.github/workflows/actions/auto-request-reviews
        with:
          orgReadToken: ${{ secrets.READORG_GITHUB_TOKEN }}
          writeToken: ${{ secrets.GITHUB_TOKEN }}
          org: 'ionic-team'
          team: 'stencil'
