name: Auto Request Review

on:
  pull_request:
    types: [opened, ready_for_review, reopened]
    branches:
      - '**'

jobs:
  auto-request-review:
    name: Auto Request Review
    runs:
      using: 'node16'
      main: 'pr-assign.js'
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
