name: Bundler Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      build_name:
        description: Name for the build, used to resolve the correct build artifact
        required: true
        type: string

jobs:
  bundler_tests:
    name: Verify Bundlers
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: ${{ inputs.build_name }}
          path: .
          filename: stencil-core-build.zip

      - name: Bundler Tests
        run: npm run test.bundlers
        shell: bash

      - name: Check Git Context
        uses: ./.github/workflows/actions/check-git-context
