name: Bundler Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  bundler_tests:
    name: Verify Bundlers
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout Code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: stencil-core
          path: .
          filename: stencil-core-build.zip

      - name: Bundler Tests
        run: npm run test.bundlers
        shell: bash

      - name: Check Git Context
        uses: ./.github/workflows/actions/check-git-context
